package com.owuor.educue.finance.enums;

public enum TransactionType {
    TUITION_BILL,
    ACCOMMODATION_BILL,
    PENALTY_FEE,
    PAYMENT_MPESA,
    PAYMENT_BANK,
    PAYMENT_CASH,
    BURSARY_ALLOCATION,
    FEE_WAIVER,
    FEES_INVOICE,
    RESIT_FEE,
    RETAKE_FEE,
    GRADUATION_FEE,
    MANUAL_DEBIT,
    SPONSOR_CREDIT,
    LOAN_CREDIT,
    MANUAL_CREDIT,
    REVERSAL,
    MIGRATION_OPENING_DEBIT,
    MIGRATION_OPENING_CREDIT
}
