package com.owuor.educue.finance.claims;
import com.owuor.educue.students.entity.Student;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import org.springframework.stereotype.Component;import java.io.*;import java.math.BigDecimal;import java.util.*;
@Component public class DebitClaimSpreadsheet {
 public record Row(int number,Long studentId,String admission,String studentName,BigDecimal amount,String status,String message){}
 public byte[] source(List<Row> rows,String title,String reason){try(var book=new XSSFWorkbook();var out=new ByteArrayOutputStream()){var meta=book.createSheet("Claim Summary");meta.createRow(0).createCell(0).setCellValue("Title");meta.getRow(0).createCell(1).setCellValue(title);meta.createRow(1).createCell(0).setCellValue("Reason");meta.getRow(1).createCell(1).setCellValue(reason);var sheet=book.createSheet("Debit Claims");header(sheet,"Row","Student ID","Admission Number","Student Name","Amount");int i=1;for(var r:rows){var x=sheet.createRow(i++);x.createCell(0).setCellValue(r.number());x.createCell(1).setCellValue(r.studentId());x.createCell(2).setCellValue(r.admission());x.createCell(3).setCellValue(r.studentName());x.createCell(4).setCellValue(r.amount().doubleValue());}for(int c=0;c<5;c++)sheet.autoSizeColumn(c);book.write(out);return out.toByteArray();}catch(Exception e){throw new IllegalStateException("Could not generate debit claim spreadsheet",e);}}
 public List<Row> read(InputStream input){try(var book=new XSSFWorkbook(input)){var sheet=book.getSheet("Debit Claims");List<Row> rows=new ArrayList<>();for(int i=1;i<=sheet.getLastRowNum();i++){var x=sheet.getRow(i);if(x==null)continue;rows.add(new Row((int)x.getCell(0).getNumericCellValue(),(long)x.getCell(1).getNumericCellValue(),x.getCell(2).getStringCellValue(),x.getCell(3).getStringCellValue(),BigDecimal.valueOf(x.getCell(4).getNumericCellValue()),null,null));}return rows;}catch(Exception e){throw new IllegalStateException("Could not read debit claim spreadsheet",e);}}
 public byte[] result(List<Row> rows){try(var book=new XSSFWorkbook();var out=new ByteArrayOutputStream()){var sheet=book.createSheet("Posting Results");header(sheet,"Row","Student ID","Admission Number","Student Name","Amount","Status","Message");int i=1;for(var r:rows){var x=sheet.createRow(i++);x.createCell(0).setCellValue(r.number());x.createCell(1).setCellValue(r.studentId());x.createCell(2).setCellValue(r.admission());x.createCell(3).setCellValue(r.studentName());x.createCell(4).setCellValue(r.amount().doubleValue());x.createCell(5).setCellValue(r.status());x.createCell(6).setCellValue(r.message());}for(int c=0;c<7;c++)sheet.autoSizeColumn(c);book.write(out);return out.toByteArray();}catch(Exception e){throw new IllegalStateException("Could not generate debit claim result",e);}}
 private void header(org.apache.poi.ss.usermodel.Sheet s,String... values){var row=s.createRow(0);for(int i=0;i<values.length;i++){var c=row.createCell(i);c.setCellValue(values[i]);}}
}
