package com.owuor.educue.finance.claims;
import com.owuor.educue.common.storage.FileStorageService;import com.owuor.educue.students.repository.StudentRepository;import com.owuor.educue.users.entity.User;import jakarta.persistence.EntityNotFoundException;import lombok.RequiredArgsConstructor;import org.springframework.core.io.Resource;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.LocalDateTime;import java.util.*;
@Service @RequiredArgsConstructor public class DebitClaimService {
 private final DebitClaimBatchRepository repository;private final StudentRepository students;private final FileStorageService storage;private final DebitClaimSpreadsheet spreadsheet;
 @Transactional public DebitClaimDtos.View create(DebitClaimDtos.Create request,User creator){
  String category=switch(request.category().toUpperCase()){case "ACCOMMODATION","DAMAGE","LOST_PROPERTY","LIBRARY","OTHER"->request.category().toUpperCase();default->throw new IllegalArgumentException("Unsupported claim category");};
  LinkedHashMap<Long,BigDecimal> selected=new LinkedHashMap<>();if(request.allActiveStudents()){if(request.amountForAll()==null)throw new IllegalArgumentException("Amount for all students is required");students.findAllWithActiveEnrollment().forEach(s->selected.put(s.getId(),request.amountForAll()));}else{if(request.items()==null||request.items().isEmpty())throw new IllegalArgumentException("Select at least one student");request.items().forEach(i->selected.put(i.studentId(),i.amount()));}
  var rows=new ArrayList<DebitClaimSpreadsheet.Row>();int number=1;BigDecimal total=BigDecimal.ZERO;for(var item:selected.entrySet()){var student=students.findById(item.getKey()).orElseThrow(()->new EntityNotFoundException("Student not found: "+item.getKey()));rows.add(new DebitClaimSpreadsheet.Row(number++,student.getId(),student.getAdmissionNumber(),student.getFullName(),item.getValue(),null,null));total=total.add(item.getValue());}
  var batch=new DebitClaimBatch();batch.setTitle(request.title().trim());batch.setCategory(category);batch.setReason(request.reason().trim());batch.setCreatedBy(creator);batch.setTotalRows(rows.size());batch.setTotalAmount(total);byte[] bytes=spreadsheet.source(rows,batch.getTitle(),batch.getReason());batch.setSourceUrl(storage.store(bytes,"debit-claim-"+batch.getUuid()+".xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","debit-claims/"+batch.getUuid()));return view(repository.save(batch));
 }
 @Transactional public DebitClaimDtos.View confirm(UUID uuid,User finance){var b=find(uuid);if(!Set.of("DRAFT","FAILED","COMPLETED_WITH_ERRORS").contains(b.getStatus()))throw new IllegalStateException("Only a draft or failed claim batch can be confirmed");b.setConfirmedBy(finance);b.setConfirmedAt(LocalDateTime.now());b.setStatus("QUEUED");b.setLastError(null);b.setProcessedRows(0);b.setSuccessfulRows(0);b.setFailedRows(0);return view(repository.save(b));}
 @Transactional(readOnly=true) public List<DebitClaimDtos.View> list(User user){boolean all=Set.of("FINANCE","ADMIN").contains(user.getRole().getName());return repository.findAllByOrderByCreatedAtDesc().stream().filter(b->all||b.getCreatedBy().getId().equals(user.getId())).map(this::view).toList();}
 @Transactional(readOnly=true) public DebitClaimDtos.View one(UUID uuid,User user){var b=find(uuid);authorize(b,user);return view(b);}
 @Transactional(readOnly=true) public Resource file(UUID uuid,String type,User user){var b=find(uuid);authorize(b,user);String key="result".equals(type)?b.getResultUrl():b.getSourceUrl();if(key==null)throw new EntityNotFoundException("Claim file is not ready");return storage.load(key);}
 void authorize(DebitClaimBatch b,User user){if(!Set.of("FINANCE","ADMIN").contains(user.getRole().getName())&&!b.getCreatedBy().getId().equals(user.getId()))throw new org.springframework.security.access.AccessDeniedException("Claim batch belongs to another officer");}
 DebitClaimBatch find(UUID uuid){return repository.findByUuid(uuid).orElseThrow(()->new EntityNotFoundException("Debit claim batch not found"));}
 DebitClaimDtos.View view(DebitClaimBatch b){return new DebitClaimDtos.View(b.getUuid(),b.getTitle(),b.getCategory(),b.getReason(),b.getStatus(),b.getTotalRows(),b.getProcessedRows(),b.getSuccessfulRows(),b.getFailedRows(),b.getTotalAmount(),"/api/debit-claims/"+b.getUuid()+"/files/source",b.getResultUrl()==null?null:"/api/debit-claims/"+b.getUuid()+"/files/result",b.getCreatedBy().getFullName(),b.getConfirmedBy()==null?null:b.getConfirmedBy().getFullName(),b.getLastError(),b.getCreatedAt(),b.getCompletedAt());}
}
