package com.owuor.educue.graduation.enums;

public enum GraduationCandidateStatus {
    NOT_STARTED, DRAFT, PROVISIONAL, DETAILS_CONFIRMED, CLEARANCE_IN_PROGRESS,
    FINANCE_REVIEW, REGISTRAR_REVIEW, CLEARANCE_COMPLETE,
    SUBMITTED_TO_REGISTRAR, APPROVED_FOR_GRADUATION,
    ACTION_REQUIRED, REMOVED, GRADUATED, CONFERRED,
    REJECTED, CANCELLED,
    // Legacy values retained while existing records are migrated.
    APPLIED, READY_FOR_GRADUATION_REVIEW, PENDING_GRADUATION, APPROVED
}
