package com.owuor.educue.certificate.service;
import com.owuor.educue.certificate.entity.*;import com.owuor.educue.certificate.enums.*;import com.owuor.educue.certificate.repository.*;import com.owuor.educue.graduation.repository.*;import com.owuor.educue.common.storage.FileStorageService;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;import java.security.*;import java.time.*;import java.util.HexFormat;
@Service @RequiredArgsConstructor public class CertificateItemWorker{private final CertificateGenerationJobRepository jobRepository;private final GraduationCertificateRepository certificateRepository;private final GraduationBatchCandidateRepository candidateRepository;private final CertificatePdfRenderer renderer;private final FileStorageService storage;
 @Transactional(propagation=Propagation.REQUIRES_NEW) public void generate(Long jobId,Long candidateId){
  var job=jobRepository.findById(jobId).orElseThrow();var candidate=candidateRepository.findById(candidateId).orElseThrow();
  GraduationCertificate certificate=certificateRepository.findByApplicationId(candidate.getApplication().getId()).orElseGet(()->{
   GraduationCertificate c=new GraduationCertificate();var application=candidate.getApplication();var enrollment=application.getEnrollment();var course=enrollment.getCourse();
   c.setJob(job);c.setApplication(application);c.setStudentName(enrollment.getStudent().getFullName());c.setAdmissionNumber(enrollment.getStudent().getAdmissionNumber());c.setCourseCode(course.getCode());c.setCourseName(course.getName());c.setAwardTitle(course.getAwardTitle()==null||course.getAwardTitle().isBlank()?course.getName():course.getAwardTitle());c.setAwardClassification(application.getAwardClassification()==null?null:application.getAwardClassification().getDisplayName());c.setGraduationDate(application.getGraduationDate());c.setCertificateNumber("CERT-"+application.getGraduationDate().getYear()+"-"+String.format("%07d",application.getId()));return certificateRepository.save(c);
  });
  try{if(certificate.getStatus()!=CertificateStatus.GENERATED){certificate.setStatus(CertificateStatus.GENERATING);certificateRepository.save(certificate);byte[] pdf=renderer.render(certificate);String url=storage.store(pdf,certificate.getCertificateNumber()+".pdf","application/pdf","educue/graduation-certificates/"+job.getUuid());certificate.setStorageUrl(url);certificate.setFileSize((long)pdf.length);certificate.setChecksumSha256(HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(pdf)));certificate.setGeneratedAt(LocalDateTime.now());certificate.setErrorMessage(null);certificate.setStatus(CertificateStatus.GENERATED);certificateRepository.save(certificate);}job.setSuccessfulCertificates(job.getSuccessfulCertificates()+1);}catch(Exception e){certificate.setStatus(CertificateStatus.FAILED);certificate.setErrorMessage(message(e));certificateRepository.save(certificate);job.setFailedCertificates(job.getFailedCertificates()+1);}job.setProcessedCertificates(job.getProcessedCertificates()+1);jobRepository.save(job);
 }
 private String message(Exception e){String value=e.getMessage()==null?"Certificate generation failed":e.getMessage();return value.substring(0,Math.min(1000,value.length()));}
}
