package com.owuor.educue.certificate.service;
import com.owuor.educue.certificate.dto.CertificateDtos.*;import com.owuor.educue.certificate.entity.*;import com.owuor.educue.certificate.enums.*;import com.owuor.educue.certificate.repository.*;import com.owuor.educue.graduation.enums.*;import com.owuor.educue.graduation.repository.*;import com.owuor.educue.users.entity.User;import jakarta.transaction.Transactional;import lombok.RequiredArgsConstructor;import org.springframework.context.ApplicationEventPublisher;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.web.server.ResponseStatusException;import java.util.*;
@Service @RequiredArgsConstructor public class CertificateJobService{
 private final CertificateGenerationJobRepository jobRepository;private final GraduationCertificateRepository certificateRepository;private final GraduationBatchRepository batchRepository;private final GraduationBatchCandidateRepository candidateRepository;private final ApplicationEventPublisher events;
 @Transactional public Job create(CreateJobRequest request,User user){var batch=batchRepository.findByUuid(request.batchUuid()).orElseThrow(()->notFound("Graduating class not found"));if(batch.getStatus()!=GraduationBatchStatus.CONFERRED&&batch.getStatus()!=GraduationBatchStatus.COMPLETED_WITH_ERRORS)throw conflict("Certificates can only be generated after awards have been conferred");long total=candidateRepository.countByBatchIdAndStatus(batch.getId(),GraduationBatchCandidateStatus.GRADUATED);if(total==0)throw conflict("This class has no successfully graduated candidates");var existing=jobRepository.findByBatchId(batch.getId());if(existing.isPresent()){var job=existing.get();if(job.getStatus()==CertificateJobStatus.PROCESSING||job.getStatus()==CertificateJobStatus.QUEUED||job.getStatus()==CertificateJobStatus.COMPLETED)return dto(job);reset(job,user,(int)total);job=jobRepository.save(job);events.publishEvent(new GenerateCertificatesEvent(job.getId()));return dto(job);}var job=new CertificateGenerationJob();job.setBatch(batch);job.setRequestedBy(user);job.setTotalCertificates((int)total);job=jobRepository.save(job);events.publishEvent(new GenerateCertificatesEvent(job.getId()));return dto(job);}
 @Transactional public Page<Job> jobs(Pageable pageable){return jobRepository.findAllByOrderByRequestedAtDesc(pageable).map(this::dto);}
 @Transactional public Job job(UUID uuid){return dto(entity(uuid));}
 @Transactional public Page<Certificate> certificates(UUID jobUuid,String search,String status,Pageable pageable){var job=entity(jobUuid);Specification<GraduationCertificate> spec=(root,query,cb)->cb.equal(root.get("job").get("id"),job.getId());if(search!=null&&!search.isBlank()){String value="%"+search.trim().toLowerCase()+"%";spec=spec.and((root,query,cb)->cb.or(cb.like(cb.lower(root.get("studentName")),value),cb.like(cb.lower(root.get("admissionNumber")),value)));}if(status!=null&&!status.isBlank())try{var parsed=CertificateStatus.valueOf(status);spec=spec.and((root,query,cb)->cb.equal(root.get("status"),parsed));}catch(IllegalArgumentException e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid certificate status");}return certificateRepository.findAll(spec,pageable).map(this::dto);}
 @Transactional public Certificate retry(UUID uuid){var certificate=certificateRepository.findByUuid(uuid).orElseThrow(()->notFound("Certificate not found"));if(certificate.getStatus()!=CertificateStatus.FAILED)throw conflict("Only failed certificates can be retried");var job=certificate.getJob();var candidate=candidateRepository.findByBatchIdAndApplicationId(job.getBatch().getId(),certificate.getApplication().getId()).orElseThrow(()->notFound("Graduating class candidate not found"));certificate.setStatus(CertificateStatus.PENDING);certificate.setErrorMessage(null);certificateRepository.save(certificate);job.setStatus(CertificateJobStatus.PROCESSING);job.setCompletedAt(null);job.setProcessedCertificates(Math.max(0,job.getProcessedCertificates()-1));job.setFailedCertificates(Math.max(0,job.getFailedCertificates()-1));jobRepository.save(job);events.publishEvent(new RetryCertificateEvent(job.getId(),candidate.getId()));return dto(certificate);}
 @Transactional public Certificate mine(User user){return certificateRepository.findByApplicationEnrollmentStudentUserId(user.getId()).map(this::dto).orElseThrow(()->notFound("Your graduation certificate has not been scheduled for generation"));}
 @Transactional public String downloadUrl(UUID certificateUuid){var c=certificateRepository.findByUuid(certificateUuid).orElseThrow(()->notFound("Certificate not found"));if(c.getStatus()!=CertificateStatus.GENERATED||c.getStorageUrl()==null)throw conflict("Certificate file is not ready");return c.getStorageUrl();}
 private void reset(CertificateGenerationJob j,User user,int total){j.setStatus(CertificateJobStatus.QUEUED);j.setErrorMessage(null);j.setStartedAt(null);j.setCompletedAt(null);j.setProcessedCertificates(0);j.setSuccessfulCertificates(0);j.setFailedCertificates(0);j.setRequestedBy(user);j.setTotalCertificates(total);}
 private CertificateGenerationJob entity(UUID uuid){return jobRepository.findByUuid(uuid).orElseThrow(()->notFound("Certificate generation job not found"));}
 private Job dto(CertificateGenerationJob j){return new Job(j.getUuid(),j.getBatch().getUuid(),j.getBatch().getName(),j.getBatch().getAcademicYear().getCode(),j.getStatus().name(),j.getTotalCertificates(),j.getProcessedCertificates(),j.getSuccessfulCertificates(),j.getFailedCertificates(),j.getRequestedBy().getFullName(),j.getRequestedAt(),j.getStartedAt(),j.getCompletedAt(),j.getErrorMessage());}
 private Certificate dto(GraduationCertificate c){return new Certificate(c.getUuid(),c.getCertificateNumber(),c.getStudentName(),c.getAdmissionNumber(),c.getCourseCode(),c.getAwardTitle(),c.getStatus().name(),c.getFileSize(),c.getErrorMessage(),c.getGeneratedAt(),c.getStatus()==CertificateStatus.GENERATED?c.getStorageUrl():null);}
 private ResponseStatusException notFound(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}public record GenerateCertificatesEvent(Long jobId){}public record RetryCertificateEvent(Long jobId,Long candidateId){}
}
