package com.owuor.educue.clearance.service;
import com.owuor.educue.clearance.dto.ClearanceDtos.*; import com.owuor.educue.clearance.entity.*; import com.owuor.educue.clearance.enums.*; import com.owuor.educue.clearance.repository.*;
import com.owuor.educue.institution.entity.*; import com.owuor.educue.institution.enums.AcademicActivityType; import com.owuor.educue.institution.repository.*; import com.owuor.educue.institution.service.AcademicActivityDeadlineService;
import com.owuor.educue.students.entity.Enrollment; import com.owuor.educue.students.enums.EnrollmentStatus; import com.owuor.educue.students.repository.EnrollmentRepository; import com.owuor.educue.users.entity.User;
import com.owuor.educue.graduation.repository.GraduationApplicationRepository; import com.owuor.educue.graduation.entity.GraduationApplication; import com.owuor.educue.graduation.enums.*; import com.owuor.educue.finance.repository.FeeLedgerRepository;
import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification;
import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor
public class ClearanceService {
 private final AcademicYearClearanceDepartmentRepository configRepository; private final ClearanceApplicationRepository applicationRepository; private final ClearanceCheckRepository checkRepository;
 private final AcademicYearRepository yearRepository; private final DepartmentRepository departmentRepository; private final EnrollmentRepository enrollmentRepository; private final AcademicActivityDeadlineRepository deadlineRepository;
 private final GraduationApplicationRepository graduationRepository; private final FeeLedgerRepository ledgerRepository;
 @Transactional public List<DepartmentItem> configureYear(UUID yearUuid,YearDepartmentsRequest request){AcademicYear y=year(yearUuid);configRepository.deleteByAcademicYearId(y.getId());int i=1;for(Long id:new LinkedHashSet<>(request.departmentIds())){Department d=departmentRepository.findById(id).orElseThrow(()->notFound("Department not found"));if(isRegistrar(d))throw conflict("Registrar is a graduation approval stage and cannot be configured as a clearance department");var x=new AcademicYearClearanceDepartment();x.setAcademicYear(y);x.setDepartment(d);x.setDisplayOrder(i++);x.setStage(isFinance(d)?ClearanceDepartmentStage.FINANCE:ClearanceDepartmentStage.GENERAL);configRepository.save(x);}return configured(y);}
 @Transactional(readOnly=true) public List<DepartmentItem> yearDepartments(UUID yearUuid){return configured(year(yearUuid));}
 @Transactional(readOnly=true) public Preview preview(User user){Enrollment e=enrollment(user);AcademicYear y=e.getCurrentAcademicYear();var deadline=deadline(y);var offices=studentDepartments(y,e.getCourse().getDepartment());var candidate=graduationRepository.findFirstByEnrollmentIdOrderByGraduationListAcademicYearStartDateDesc(e.getId()).orElse(null);String blocker=candidate==null||candidate.getDetailsConfirmedAt()==null?"Confirm your provisional graduation details before applying for clearance":null;if(blocker==null&&e.getStatus()!=EnrollmentStatus.ACTIVE)blocker="Only active students can submit a new clearance application";if(blocker==null)blocker=windowBlocker(deadline);if(blocker==null&&offices.isEmpty())blocker="No graduation-clearance departments are configured for this academic year";boolean visible=candidate!=null&&candidate.getDetailsConfirmedAt()!=null;return new Preview(visible,blocker==null,blocker==null?"Graduation clearance applications are open":blocker,deadline==null?null:window(deadline),e.getCourse().getCode(),e.getCourse().getName(),offices);}
 @Transactional public ApplicationResponse apply(User user,ApplyRequest request){Enrollment e=enrollmentRepository.findByStudentUserIdForUpdate(user.getId()).orElseThrow(()->notFound("Student enrollment not found"));if(e.getStatus()!=EnrollmentStatus.ACTIVE)throw conflict("Only active students can apply for clearance");var candidate=latestCandidateForUpdate(e.getId());if(candidate.getDetailsConfirmedAt()==null)throw conflict("Confirm graduation details before applying for clearance");AcademicYear y=e.getCurrentAcademicYear();String blocker=windowBlocker(deadline(y));if(blocker!=null)throw conflict(blocker);List<DepartmentItem> allowed=studentDepartments(y,e.getCourse().getDepartment());Map<Long,AcademicYearClearanceDepartment> configured=configRepository.findByAcademicYearIdOrderByDisplayOrderAsc(y.getId()).stream().collect(java.util.stream.Collectors.toMap(x->x.getDepartment().getId(),x->x));var app=applicationRepository.findByEnrollmentIdAndAcademicYearId(e.getId(),y.getId()).orElseGet(()->{var a=new ClearanceApplication();a.setEnrollment(e);a.setAcademicYear(y);a.setStatus(ClearanceApplicationStatus.IN_PROGRESS);return a;});Set<Long> existing=new HashSet<>();app.getChecks().forEach(x->existing.add(x.getDepartment().getId()));for(DepartmentItem item:allowed)if(existing.add(item.id())){var c=new ClearanceCheck();c.setDepartment(departmentRepository.getReferenceById(item.id()));c.setDisplayOrder(item.displayOrder());var cfg=configured.get(item.id());c.setStage(cfg==null?ClearanceDepartmentStage.GENERAL:cfg.getStage());c.setMandatory(cfg==null||cfg.isMandatory());app.addCheck(c);}candidate.setStatus(GraduationApplicationStatus.CLEARANCE_IN_PROGRESS);candidate.setClearanceStage(GraduationClearanceStage.GENERAL_CLEARANCE);candidate.setClearanceComplete(false);candidate.setFinanceCleared(false);graduationRepository.save(candidate);return response(applicationRepository.save(app));}
 @Transactional(readOnly=true) public ApplicationResponse mine(User u){Enrollment e=enrollment(u);return applicationRepository.findFirstByEnrollmentIdOrderByAppliedAtDesc(e.getId()).map(this::response).orElseThrow(()->notFound("Clearance application not found"));}
 @Transactional(readOnly=true) public Page<OfficerRequest> officerRequests(User u,String search,Long courseId,Long departmentId,String status,Pageable pageable){
  Specification<ClearanceCheck> spec=(root,query,cb)->cb.conjunction();
  if(!isAdmin(u)){Long own=requiredDepartment(u).getId();spec=spec.and((root,query,cb)->cb.equal(root.get("department").get("id"),own));}
  if(departmentId!=null)spec=spec.and((root,query,cb)->cb.equal(root.get("department").get("id"),departmentId));
  if(courseId!=null)spec=spec.and((root,query,cb)->cb.equal(root.get("application").get("enrollment").get("course").get("id"),courseId));
  if(search!=null&&!search.isBlank()){String value="%"+search.trim().toLowerCase()+"%";spec=spec.and((root,query,cb)->cb.or(cb.like(cb.lower(root.get("application").get("enrollment").get("student").get("fullName")),value),cb.like(cb.lower(root.get("application").get("enrollment").get("student").get("admissionNumber")),value),cb.like(cb.lower(root.get("application").get("enrollment").get("student").get("email")),value)));}
  if(status!=null&&!status.isBlank())try{ClearanceCheckStatus parsed=ClearanceCheckStatus.valueOf(status);spec=spec.and((root,query,cb)->cb.equal(root.get("status"),parsed));}catch(IllegalArgumentException x){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid clearance status");}
  if("FINANCE".equals(u.getRole().getName())) spec=spec.and((root,query,cb)->{var sq=query.subquery(Long.class);var g=sq.from(com.owuor.educue.graduation.entity.GraduationApplication.class);sq.select(g.get("id")).where(cb.equal(g.get("enrollment").get("id"),root.get("application").get("enrollment").get("id")),cb.equal(g.get("clearanceStage"),GraduationClearanceStage.FINANCE_REVIEW));return cb.and(cb.equal(root.get("stage"),ClearanceDepartmentStage.FINANCE),cb.exists(sq));});
  return checkRepository.findAll(spec,pageable).map(this::officer);
 }
 @Transactional public ApplicationResponse review(Long id,ReviewRequest req,User u){
  var check=checkRepository.findByIdForUpdate(id).orElseThrow(()->notFound("Clearance request not found"));
  if(!isAdmin(u)&&!check.getDepartment().getId().equals(requiredDepartment(u).getId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"This request belongs to another department");
  ClearanceCheckStatus decision;try{decision=ClearanceCheckStatus.valueOf(req.status());}catch(Exception x){throw conflict("Invalid review status");}
  if(decision==ClearanceCheckStatus.PENDING)throw conflict("Pending is not a review decision");
  if((decision==ClearanceCheckStatus.ACTION_REQUIRED||decision==ClearanceCheckStatus.REJECTED)&&(req.remarks()==null||req.remarks().isBlank()))throw conflict("Remarks are required");
  var application=check.getApplication();
  var candidate=latestCandidateForUpdate(application.getEnrollment().getId());
  boolean finance=check.getStage()==ClearanceDepartmentStage.FINANCE;
  if(finance&&candidate.getClearanceStage()!=GraduationClearanceStage.FINANCE_REVIEW)throw conflict("This candidate has not reached Finance review");
  if(!finance&&candidate.getClearanceStage()!=GraduationClearanceStage.GENERAL_CLEARANCE)throw conflict("General clearance is no longer open for this candidate");
  check.setStatus(decision);check.setRemarks(req.remarks()==null?null:req.remarks().trim());check.setReviewedBy(u);check.setReviewedAt(LocalDateTime.now());checkRepository.saveAndFlush(check);
  boolean blockers=checkRepository.existsByApplicationIdAndStageAndMandatoryTrueAndStatusNot(application.getId(),ClearanceDepartmentStage.GENERAL,ClearanceCheckStatus.CLEARED);
  if(finance&&decision==ClearanceCheckStatus.CLEARED){
   if(blockers)throw conflict("Mandatory departmental clearance is incomplete");
   if(candidate.getDetailsConfirmedAt()==null)throw conflict("Graduation details are not confirmed");
   if(candidate.getLedgerEntry()==null)throw conflict("Graduation fee has not been charged");
   if(ledgerRepository.getOutstandingBalance(application.getEnrollment().getStudent().getId()).signum()>0)throw conflict("Graduation fee or required account balance is not settled");
   candidate.setFinanceCleared(true);candidate.setClearanceComplete(true);candidate.setClearanceStage(GraduationClearanceStage.REGISTRAR_REVIEW);candidate.setStatus(GraduationApplicationStatus.CLEARANCE_COMPLETE);application.setStatus(ClearanceApplicationStatus.CLEARED);application.setCompletedAt(LocalDateTime.now());
  }else if(finance){
   candidate.setFinanceCleared(false);candidate.setClearanceComplete(false);candidate.setClearanceStage(GraduationClearanceStage.FINANCE_REVIEW);candidate.setStatus(GraduationApplicationStatus.ACTION_REQUIRED);application.setStatus(ClearanceApplicationStatus.ACTION_REQUIRED);application.setCompletedAt(null);
  }else if(blockers){
   candidate.setClearanceStage(GraduationClearanceStage.GENERAL_CLEARANCE);candidate.setStatus(decision==ClearanceCheckStatus.CLEARED?GraduationApplicationStatus.CLEARANCE_IN_PROGRESS:GraduationApplicationStatus.ACTION_REQUIRED);candidate.setClearanceComplete(false);candidate.setFinanceCleared(false);application.setStatus(decision==ClearanceCheckStatus.CLEARED?ClearanceApplicationStatus.IN_PROGRESS:ClearanceApplicationStatus.ACTION_REQUIRED);application.setCompletedAt(null);
  }else{
   if(!checkRepository.existsByApplicationIdAndStage(application.getId(),ClearanceDepartmentStage.FINANCE))throw conflict("Finance clearance is not configured for this application");
   candidate.setClearanceStage(GraduationClearanceStage.FINANCE_REVIEW);candidate.setStatus(GraduationApplicationStatus.CLEARANCE_IN_PROGRESS);candidate.setClearanceComplete(false);candidate.setFinanceCleared(false);application.setStatus(ClearanceApplicationStatus.IN_PROGRESS);application.setCompletedAt(null);
  }
  graduationRepository.save(candidate);return response(applicationRepository.save(application));
 }
 private List<DepartmentItem> configured(AcademicYear y){return configRepository.findByAcademicYearIdOrderByDisplayOrderAsc(y.getId()).stream().filter(x->!isRegistrar(x.getDepartment())).map(x->new DepartmentItem(x.getDepartment().getId(),x.getDepartment().getName(),x.getDisplayOrder(),true)).toList();}
 private List<DepartmentItem> studentDepartments(AcademicYear y,Department own){LinkedHashMap<Long,Department> map=new LinkedHashMap<>();if(!isRegistrar(own))map.put(own.getId(),own);configRepository.findByAcademicYearIdOrderByDisplayOrderAsc(y.getId()).forEach(x->{if(!isRegistrar(x.getDepartment()))map.putIfAbsent(x.getDepartment().getId(),x.getDepartment());});List<Department> ordered=new ArrayList<>(map.values());ordered.sort(Comparator.comparing(d->isFinance(d)?1:0));int[] i={0};return ordered.stream().map(d->new DepartmentItem(d.getId(),d.getName(),++i[0],true)).toList();}
 private AcademicActivityDeadline deadline(AcademicYear y){return deadlineRepository.findByAcademicYearIdAndActivityType(y.getId(),AcademicActivityType.CLEARANCE_APPLICATION).orElse(null);} private String windowBlocker(AcademicActivityDeadline d){if(d==null||!d.isActive())return "Clearance dates have not been configured";LocalDateTime n=LocalDateTime.now();if(d.getStartsAt()!=null&&n.isBefore(d.getStartsAt()))return "Clearance opens on "+d.getStartsAt();if(n.isAfter(d.getDeadlineAt()))return "Clearance closed on "+d.getDeadlineAt();return null;}
 private String finalBlocker(Enrollment e){var current=e.getCurrentCourseAcademicPeriod();if(current==null)return "Your current academic period has not been configured";return current.getNextPeriod()!=null?"Clearance becomes available in your final academic period":null;}
 private DeadlineWindow window(AcademicActivityDeadline d){return new DeadlineWindow(d.getUuid(),d.getAcademicYear().getCode(),d.getStartsAt(),d.getDeadlineAt(),d.isActive());}
 private ApplicationResponse response(ClearanceApplication a){var e=a.getEnrollment();var d=deadline(a.getAcademicYear());return new ApplicationResponse(a.getUuid(),a.getStatus().name(),e.getStudent().getAdmissionNumber(),e.getStudent().getFullName(),e.getCourse().getCode(),e.getCourse().getName(),d==null?null:window(d),a.getAppliedAt(),a.getCompletedAt(),a.getChecks().stream().map(c->new CheckItem(c.getId(),c.getDepartment().getId(),c.getDepartment().getName(),c.getStatus().name(),c.getRemarks(),c.getReviewedBy()==null?null:c.getReviewedBy().getFullName(),c.getReviewedAt())).toList());}
 private OfficerRequest officer(ClearanceCheck c){var a=c.getApplication();var e=a.getEnrollment();return new OfficerRequest(c.getId(),a.getUuid(),e.getStudent().getAdmissionNumber(),e.getStudent().getFullName(),e.getCourse().getCode(),e.getCourse().getName(),a.getAcademicYear().getCode(),c.getDepartment().getName(),c.getStatus().name(),c.getRemarks(),a.getAppliedAt());}
 private GraduationApplication latestCandidateForUpdate(Long enrollmentId){var latest=graduationRepository.findFirstByEnrollmentIdOrderByGraduationListAcademicYearStartDateDesc(enrollmentId).orElseThrow(()->conflict("Candidate is not on a graduation list"));return graduationRepository.findDetailedByIdForUpdate(latest.getId()).orElseThrow(()->conflict("Candidate is not on a graduation list"));}
 private Enrollment enrollment(User u){return enrollmentRepository.findByStudentUserId(u.getId()).orElseThrow(()->notFound("Student enrollment not found"));} private AcademicYear year(UUID id){return yearRepository.findByUuid(id).orElseThrow(()->notFound("Academic year not found"));}
 private Department requiredDepartment(User u){if(u.getDepartment()!=null)return u.getDepartment();if("FINANCE".equals(u.getRole().getName()))return departmentRepository.findByNameIgnoreCase("Finance").orElseThrow(()->conflict("Finance department is not configured"));throw conflict("Your account is not assigned to a department");} private boolean isAdmin(User u){return "ADMIN".equals(u.getRole().getName());}
 private boolean isFinance(Department d){return d!=null&&d.getName()!=null&&d.getName().trim().equalsIgnoreCase("Finance");}
 private boolean isRegistrar(Department d){return d!=null&&d.getName()!=null&&d.getName().trim().equalsIgnoreCase("Registrar");}
 private ResponseStatusException conflict(String x){return new ResponseStatusException(HttpStatus.CONFLICT,x);}private ResponseStatusException notFound(String x){return new ResponseStatusException(HttpStatus.NOT_FOUND,x);}
}
