package com.owuor.educue.graduation.service;
import com.owuor.educue.finance.repository.FeeLedgerRepository; import com.owuor.educue.graduation.entity.*; import com.owuor.educue.graduation.enums.*; import com.owuor.educue.graduation.repository.*; import com.owuor.educue.students.enums.EnrollmentStatus; import com.owuor.educue.students.repository.EnrollmentRepository; import com.owuor.educue.users.repository.UserRepository;
import lombok.RequiredArgsConstructor; import org.springframework.scheduling.annotation.Async; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import org.springframework.transaction.event.*; import java.math.BigDecimal; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor
public class GraduationBatchProcessor {
 private final GraduationBatchRepository batchRepository;private final GraduationBatchCandidateRepository candidateRepository;private final GraduationApplicationRepository applicationRepository;private final EnrollmentRepository enrollmentRepository;private final FeeLedgerRepository ledgerRepository;private final UserRepository userRepository;private final GraduationCandidateProcessor candidateProcessor;
 @Async @TransactionalEventListener(phase=TransactionPhase.AFTER_COMMIT)
 public void process(GraduationBatchService.ConferBatchEvent event){var pending=candidateRepository.findByBatchIdAndStatusOrderByIdAsc(event.batchId(),GraduationBatchCandidateStatus.PENDING).stream().map(GraduationBatchCandidate::getId).toList();for(Long id:pending)candidateProcessor.process(id,event.userId());finish(event.batchId());}
 @Transactional public void finish(Long batchId){var batch=batchRepository.findById(batchId).orElseThrow();var all=candidateRepository.findByBatchIdOrderByApplicationEnrollmentCourseDepartmentNameAscApplicationEnrollmentCourseNameAscApplicationEnrollmentStudentFullNameAsc(batchId);int success=(int)all.stream().filter(c->c.getStatus()==GraduationBatchCandidateStatus.GRADUATED).count();int failures=(int)all.stream().filter(c->c.getStatus()==GraduationBatchCandidateStatus.FAILED||c.getStatus()==GraduationBatchCandidateStatus.SKIPPED).count();batch.setProcessedCandidates(success+failures);batch.setSuccessfulCandidates(success);batch.setFailedCandidates(failures);batch.setStatus(failures==0?GraduationBatchStatus.CONFERRED:GraduationBatchStatus.COMPLETED_WITH_ERRORS);batchRepository.save(batch);}
}
