-- V2: academic configuration, catalogue, admissions and intake structure

--
-- Name: academic_activity_deadlines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academic_activity_deadlines (
    id bigint NOT NULL,
    active boolean NOT NULL,
    activity_type character varying(40) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deadline_at timestamp(6) without time zone NOT NULL,
    description character varying(250),
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    academic_year_id bigint NOT NULL,
    starts_at timestamp(6) without time zone,
    CONSTRAINT academic_activity_deadlines_activity_type_check CHECK (((activity_type)::text = ANY ((ARRAY['APPLICATION_SUBMISSION'::character varying, 'STUDENT_ENROLLMENT'::character varying, 'UNIT_ADDITION'::character varying, 'UNIT_REGISTRATION'::character varying, 'FEE_SETUP'::character varying, 'RESULTS_ENTRY'::character varying, 'STUDENT_PROMOTION'::character varying, 'CLEARANCE_APPLICATION'::character varying])::text[])))
);

--
-- Name: academic_activity_deadlines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.academic_activity_deadlines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_activity_deadlines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: academic_periods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academic_periods (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(100) NOT NULL,
    period_number integer NOT NULL,
    period_type character varying(20) NOT NULL,
    periods_per_year integer NOT NULL,
    sequence_number integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    year_number integer NOT NULL,
    CONSTRAINT academic_periods_period_type_check CHECK (((period_type)::text = ANY ((ARRAY['SEMESTER'::character varying, 'TERM'::character varying, 'TRIMESTER'::character varying, 'MODULE'::character varying, 'QUARTER'::character varying, 'BLOCK'::character varying])::text[])))
);

--
-- Name: academic_periods_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.academic_periods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_periods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: academic_years; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academic_years (
    id bigint NOT NULL,
    active boolean NOT NULL,
    closed boolean NOT NULL,
    code character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current boolean NOT NULL,
    end_date date NOT NULL,
    start_date date NOT NULL,
    start_year integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL
);

--
-- Name: academic_years_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.academic_years ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_years_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: admission_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admission_jobs (
    id bigint NOT NULL,
    application_id bigint NOT NULL,
    attempt_count integer NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    job_type character varying(255) NOT NULL,
    last_error character varying(1000),
    locked_at timestamp(6) without time zone,
    max_attempts integer NOT NULL,
    next_attempt_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

--
-- Name: admission_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admission_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admission_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: application_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_documents (
    id bigint NOT NULL,
    content_type character varying(100),
    document_type character varying(30) NOT NULL,
    file_size_bytes bigint,
    original_filename character varying(255),
    s3_key character varying(500) NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    application_id bigint NOT NULL,
    CONSTRAINT application_documents_document_type_check CHECK (((document_type)::text = ANY ((ARRAY['NATIONAL_ID'::character varying, 'BIRTH_CERTIFICATE'::character varying, 'KCSE_CERTIFICATE'::character varying, 'KCSE_RESULT_SLIP'::character varying, 'PASSPORT_PHOTO'::character varying, 'OTHER'::character varying])::text[])))
);

--
-- Name: application_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.applications (
    id bigint NOT NULL,
    admission_pack_error character varying(500),
    admission_pack_generated_at timestamp(6) without time zone,
    admission_pack_key character varying(500),
    application_number character varying(40) NOT NULL,
    approved_at timestamp(6) without time zone,
    date_of_birth date,
    email character varying(150) NOT NULL,
    full_name character varying(150) NOT NULL,
    guardian_name character varying(150),
    guardian_phone character varying(20),
    national_id character varying(30),
    phone character varying(20) NOT NULL,
    review_notes character varying(500),
    reviewed_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    submitted_at timestamp(6) without time zone NOT NULL,
    version bigint NOT NULL,
    approved_by_user_id bigint,
    intake_course_id bigint NOT NULL,
    CONSTRAINT applications_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'UNDER_REVIEW'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'WAITLISTED'::character varying, 'CLOSED'::character varying])::text[])))
);

--
-- Name: applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: bulk_onboarding_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bulk_onboarding_jobs (
    id bigint NOT NULL,
    attempt_count integer NOT NULL,
    batch_id uuid NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    csv_row_json text NOT NULL,
    last_error character varying(1000),
    locked_at timestamp(6) without time zone,
    max_attempts integer NOT NULL,
    next_attempt_at timestamp(6) without time zone NOT NULL,
    row_index integer NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

--
-- Name: bulk_onboarding_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bulk_onboarding_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bulk_onboarding_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: course_academic_periods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_academic_periods (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    "position" integer NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    academic_period_id bigint NOT NULL,
    course_id bigint NOT NULL,
    next_period_id bigint,
    final_period boolean DEFAULT false NOT NULL
);

--
-- Name: course_academic_periods_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_academic_periods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_academic_periods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: course_intake_configurations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_intake_configurations (
    id bigint NOT NULL,
    academic_confirmed boolean NOT NULL,
    academic_confirmed_at timestamp(6) without time zone,
    fee_confirmed boolean NOT NULL,
    fee_confirmed_at timestamp(6) without time zone,
    version bigint NOT NULL,
    course_id bigint NOT NULL,
    intake_id bigint NOT NULL
);

--
-- Name: course_intake_configurations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_intake_configurations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_intake_configurations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: course_unit_placements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_unit_placements (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    unit_type character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    course_academic_period_id bigint NOT NULL,
    unit_id bigint NOT NULL,
    effective_from_intake_id bigint NOT NULL,
    effective_to_intake_id bigint,
    CONSTRAINT course_unit_placements_unit_type_check CHECK (((unit_type)::text = ANY ((ARRAY['CORE'::character varying, 'ELECTIVE'::character varying, 'OPTIONAL'::character varying])::text[])))
);

--
-- Name: course_unit_placements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_unit_placements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_unit_placements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id bigint NOT NULL,
    active boolean NOT NULL,
    award_title character varying(150),
    code character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    duration_unit character varying(10) NOT NULL,
    duration_value integer NOT NULL,
    name character varying(150) NOT NULL,
    qualification_type character varying(255) NOT NULL,
    study_mode character varying(255),
    total_credits integer,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    department_id bigint NOT NULL,
    CONSTRAINT courses_qualification_type_check CHECK (((qualification_type)::text = ANY ((ARRAY['CERTIFICATE'::character varying, 'DIPLOMA'::character varying, 'BACHELOR'::character varying, 'MASTERS'::character varying, 'PHD'::character varying])::text[]))),
    CONSTRAINT courses_study_mode_check CHECK (((study_mode)::text = ANY ((ARRAY['FULL_TIME'::character varying, 'PART_TIME'::character varying, 'DISTANCE'::character varying, 'ONLINE'::character varying, 'EVENING'::character varying])::text[])))
);

--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: intake_courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.intake_courses (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    intake_id bigint NOT NULL
);

--
-- Name: intake_courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.intake_courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.intake_courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: intake_sequence_number_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.intake_sequence_number_seq
    START WITH 1000
    INCREMENT BY 1000
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: SEQUENCE intake_sequence_number_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE public.intake_sequence_number_seq IS 'Generates immutable chronological sequence numbers used to order intakes and determine fee applicability.';

--
-- Name: intakes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.intakes (
    id bigint NOT NULL,
    application_deadline date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(100) NOT NULL,
    sequence_number bigint NOT NULL,
    start_date date NOT NULL,
    status character varying(20) NOT NULL,
    uuid uuid NOT NULL,
    academic_year_id bigint NOT NULL,
    CONSTRAINT intakes_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'UPCOMING'::character varying, 'OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);

--
-- Name: intakes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.intakes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.intakes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: lecturer_unit_assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lecturer_unit_assignments (
    id bigint NOT NULL,
    assigned_at timestamp(6) without time zone NOT NULL,
    enabled boolean NOT NULL,
    start_year integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    assigned_by bigint,
    course_unit_placement_id bigint NOT NULL,
    effective_from_academic_year_id bigint NOT NULL,
    effective_to_academic_year_id bigint,
    lecturer_id bigint NOT NULL
);

--
-- Name: lecturer_unit_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lecturer_unit_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lecturer_unit_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    admission_number character varying(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date_of_birth date,
    email character varying(150),
    full_name character varying(150) NOT NULL,
    guardian_name character varying(150),
    guardian_phone character varying(20),
    national_id character varying(30),
    phone character varying(20),
    user_id bigint NOT NULL
);

--
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: units; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.units (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    credit_hours integer,
    description character varying(255),
    name character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    department_id bigint NOT NULL
);

--
-- Name: units_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.units ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.units_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: academic_activity_deadlines academic_activity_deadlines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_activity_deadlines
    ADD CONSTRAINT academic_activity_deadlines_pkey PRIMARY KEY (id);

--
-- Name: academic_periods academic_periods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_periods
    ADD CONSTRAINT academic_periods_pkey PRIMARY KEY (id);

--
-- Name: academic_years academic_years_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_years
    ADD CONSTRAINT academic_years_pkey PRIMARY KEY (id);

--
-- Name: admission_jobs admission_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admission_jobs
    ADD CONSTRAINT admission_jobs_pkey PRIMARY KEY (id);

--
-- Name: application_documents application_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_documents
    ADD CONSTRAINT application_documents_pkey PRIMARY KEY (id);

--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);

--
-- Name: bulk_onboarding_jobs bulk_onboarding_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bulk_onboarding_jobs
    ADD CONSTRAINT bulk_onboarding_jobs_pkey PRIMARY KEY (id);

--
-- Name: course_academic_periods course_academic_periods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_academic_periods
    ADD CONSTRAINT course_academic_periods_pkey PRIMARY KEY (id);

--
-- Name: course_intake_configurations course_intake_configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_intake_configurations
    ADD CONSTRAINT course_intake_configurations_pkey PRIMARY KEY (id);

--
-- Name: course_unit_placements course_unit_placements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unit_placements
    ADD CONSTRAINT course_unit_placements_pkey PRIMARY KEY (id);

--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);

--
-- Name: intake_courses intake_courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intake_courses
    ADD CONSTRAINT intake_courses_pkey PRIMARY KEY (id);

--
-- Name: intakes intakes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intakes
    ADD CONSTRAINT intakes_pkey PRIMARY KEY (id);

--
-- Name: lecturer_unit_assignments lecturer_unit_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lecturer_unit_assignments
    ADD CONSTRAINT lecturer_unit_assignments_pkey PRIMARY KEY (id);

--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);

--
-- Name: academic_years uk1hhhfut6rhtnl35c404q1540b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_years
    ADD CONSTRAINT uk1hhhfut6rhtnl35c404q1540b UNIQUE (uuid);

--
-- Name: lecturer_unit_assignments uk4ifxws3bqcmh7lsoke4q1c3r3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lecturer_unit_assignments
    ADD CONSTRAINT uk4ifxws3bqcmh7lsoke4q1c3r3 UNIQUE (uuid);

--
-- Name: students uk4ijilwehsq4n3vhrdlq722lnc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uk4ijilwehsq4n3vhrdlq722lnc UNIQUE (admission_number);

--
-- Name: courses uk61og8rbqdd2y28rx2et5fdnxd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT uk61og8rbqdd2y28rx2et5fdnxd UNIQUE (code);

--
-- Name: academic_activity_deadlines uk8cgqhd40kgro3r8j0no36cyx6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_activity_deadlines
    ADD CONSTRAINT uk8cgqhd40kgro3r8j0no36cyx6 UNIQUE (uuid);

--
-- Name: units uk8kuqmk4tyaa59snvgkckvgi5d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT uk8kuqmk4tyaa59snvgkckvgi5d UNIQUE (code);

--
-- Name: academic_periods uk_academic_period_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_periods
    ADD CONSTRAINT uk_academic_period_code UNIQUE (code);

--
-- Name: academic_periods uk_academic_period_type_year_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_periods
    ADD CONSTRAINT uk_academic_period_type_year_number UNIQUE (period_type, year_number, period_number);

--
-- Name: academic_years uk_academic_years_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_years
    ADD CONSTRAINT uk_academic_years_code UNIQUE (code);

--
-- Name: academic_activity_deadlines uk_activity_deadline_year_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_activity_deadlines
    ADD CONSTRAINT uk_activity_deadline_year_type UNIQUE (academic_year_id, activity_type);

--
-- Name: course_academic_periods uk_course_academic_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_academic_periods
    ADD CONSTRAINT uk_course_academic_period UNIQUE (course_id, academic_period_id);

--
-- Name: course_intake_configurations uk_course_intake_configuration; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_intake_configurations
    ADD CONSTRAINT uk_course_intake_configuration UNIQUE (intake_id, course_id);

--
-- Name: course_academic_periods uk_course_period_next; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_academic_periods
    ADD CONSTRAINT uk_course_period_next UNIQUE (next_period_id);

--
-- Name: course_academic_periods uk_course_period_position; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_academic_periods
    ADD CONSTRAINT uk_course_period_position UNIQUE (course_id, "position");

--
-- Name: course_unit_placements uk_course_unit_placement_start; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unit_placements
    ADD CONSTRAINT uk_course_unit_placement_start UNIQUE (course_academic_period_id, unit_id, effective_from_intake_id);

--
-- Name: intake_courses uk_intake_course; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intake_courses
    ADD CONSTRAINT uk_intake_course UNIQUE (intake_id, course_id);

--
-- Name: applications ukahcxcnoc8d0ls0id5xd3pspf3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT ukahcxcnoc8d0ls0id5xd3pspf3 UNIQUE (application_number);

--
-- Name: course_unit_placements ukb522slxaw1jsxd83hei748h6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unit_placements
    ADD CONSTRAINT ukb522slxaw1jsxd83hei748h6 UNIQUE (uuid);

--
-- Name: intakes ukc0eiq6p16hxkp5dxwnw8a9y3y; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intakes
    ADD CONSTRAINT ukc0eiq6p16hxkp5dxwnw8a9y3y UNIQUE (name);

--
-- Name: courses ukcmvo2fomp8gpu8lt7428batak; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT ukcmvo2fomp8gpu8lt7428batak UNIQUE (uuid);

--
-- Name: academic_periods ukd2wbev5iuqbu0q8lqtwu7yf9e; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_periods
    ADD CONSTRAINT ukd2wbev5iuqbu0q8lqtwu7yf9e UNIQUE (uuid);

--
-- Name: students ukg4fwvutq09fjdlb4bb0byp7t; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT ukg4fwvutq09fjdlb4bb0byp7t UNIQUE (user_id);

--
-- Name: units ukhf01daakgpj12kjn96pr8ideu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT ukhf01daakgpj12kjn96pr8ideu UNIQUE (uuid);

--
-- Name: intakes ukpvowq6rory7mgyibc86cfjg2a; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intakes
    ADD CONSTRAINT ukpvowq6rory7mgyibc86cfjg2a UNIQUE (uuid);

--
-- Name: course_academic_periods ukq01m3slx8vk8w9yjohbq5tpjn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_academic_periods
    ADD CONSTRAINT ukq01m3slx8vk8w9yjohbq5tpjn UNIQUE (uuid);

--
-- Name: intakes ukrxf7yc32hx0sruasp5nk2vc1d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intakes
    ADD CONSTRAINT ukrxf7yc32hx0sruasp5nk2vc1d UNIQUE (sequence_number);

--
-- Name: units units_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_pkey PRIMARY KEY (id);

--
-- Name: admission_jobs uq_admission_jobs_application_job_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admission_jobs
    ADD CONSTRAINT uq_admission_jobs_application_job_type UNIQUE (application_id, job_type);

--
-- Name: idx_academic_period_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_academic_period_active ON public.academic_periods USING btree (active);

--
-- Name: idx_academic_period_sequence; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_academic_period_sequence ON public.academic_periods USING btree (period_type, sequence_number);

--
-- Name: idx_academic_period_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_academic_period_type ON public.academic_periods USING btree (period_type);

--
-- Name: idx_academic_years_current; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_academic_years_current ON public.academic_years USING btree (current);

--
-- Name: idx_academic_years_start_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_academic_years_start_year ON public.academic_years USING btree (start_year);

--
-- Name: idx_course_period_course; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_period_course ON public.course_academic_periods USING btree (course_id);

--
-- Name: idx_course_period_next; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_period_next ON public.course_academic_periods USING btree (next_period_id);

--
-- Name: idx_course_unit_placement_course_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_unit_placement_course_period ON public.course_unit_placements USING btree (course_academic_period_id);

--
-- Name: idx_course_unit_placement_intake_range; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_unit_placement_intake_range ON public.course_unit_placements USING btree (effective_from_intake_id, effective_to_intake_id);

--
-- Name: idx_course_unit_placement_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_unit_placement_period ON public.course_unit_placements USING btree (course_academic_period_id);

--
-- Name: idx_course_unit_placement_range; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_unit_placement_range ON public.course_unit_placements USING btree (effective_from_intake_id, effective_to_intake_id);

--
-- Name: idx_course_unit_placement_unit; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_unit_placement_unit ON public.course_unit_placements USING btree (unit_id);

--
-- Name: idx_lecturer_assignment_effective_years; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lecturer_assignment_effective_years ON public.lecturer_unit_assignments USING btree (effective_from_academic_year_id, effective_to_academic_year_id);

--
-- Name: idx_lecturer_assignment_lecturer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lecturer_assignment_lecturer ON public.lecturer_unit_assignments USING btree (lecturer_id);

--
-- Name: idx_lecturer_assignment_placement; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lecturer_assignment_placement ON public.lecturer_unit_assignments USING btree (course_unit_placement_id);

--
-- Name: applications fk4cowlwd3cbse6kckyfml61qxw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fk4cowlwd3cbse6kckyfml61qxw FOREIGN KEY (intake_course_id) REFERENCES public.intake_courses(id);

--
-- Name: lecturer_unit_assignments fk4i6y7lath97xlcch1uvs98x1o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lecturer_unit_assignments
    ADD CONSTRAINT fk4i6y7lath97xlcch1uvs98x1o FOREIGN KEY (lecturer_id) REFERENCES public.users(id);

--
-- Name: lecturer_unit_assignments fk5bb4r4lxyem77vn1kfk5wv2go; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lecturer_unit_assignments
    ADD CONSTRAINT fk5bb4r4lxyem77vn1kfk5wv2go FOREIGN KEY (assigned_by) REFERENCES public.users(id);

--
-- Name: course_unit_placements fk7lw9nfitee9vbw330qtfrlpjm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unit_placements
    ADD CONSTRAINT fk7lw9nfitee9vbw330qtfrlpjm FOREIGN KEY (unit_id) REFERENCES public.units(id);

--
-- Name: course_academic_periods fkcijca4pk2qheg6gyvyfnl4w61; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_academic_periods
    ADD CONSTRAINT fkcijca4pk2qheg6gyvyfnl4w61 FOREIGN KEY (next_period_id) REFERENCES public.course_academic_periods(id);

--
-- Name: students fkdt1cjx5ve5bdabmuuf3ibrwaq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkdt1cjx5ve5bdabmuuf3ibrwaq FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: lecturer_unit_assignments fkf542ju4q0ty9t0i1iqb30y6ui; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lecturer_unit_assignments
    ADD CONSTRAINT fkf542ju4q0ty9t0i1iqb30y6ui FOREIGN KEY (effective_to_academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: applications fkfvvpucir3tkejofwkyo5m6w6c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkfvvpucir3tkejofwkyo5m6w6c FOREIGN KEY (approved_by_user_id) REFERENCES public.users(id);

--
-- Name: lecturer_unit_assignments fkg3l49q9ya9y5jywa82gmfsegb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lecturer_unit_assignments
    ADD CONSTRAINT fkg3l49q9ya9y5jywa82gmfsegb FOREIGN KEY (effective_from_academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: course_academic_periods fkg7hojj2aq6s96d5ntoj6j6scj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_academic_periods
    ADD CONSTRAINT fkg7hojj2aq6s96d5ntoj6j6scj FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: academic_activity_deadlines fkg7qy3cf81v61plngqftwq4n61; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_activity_deadlines
    ADD CONSTRAINT fkg7qy3cf81v61plngqftwq4n61 FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: lecturer_unit_assignments fkh29g70mb76n18l2p1g5mhi68o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lecturer_unit_assignments
    ADD CONSTRAINT fkh29g70mb76n18l2p1g5mhi68o FOREIGN KEY (course_unit_placement_id) REFERENCES public.course_unit_placements(id);

--
-- Name: course_unit_placements fkho6c2k18fbqbm4jyuwj1b1awn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unit_placements
    ADD CONSTRAINT fkho6c2k18fbqbm4jyuwj1b1awn FOREIGN KEY (course_academic_period_id) REFERENCES public.course_academic_periods(id);

--
-- Name: course_intake_configurations fkidbkptqw3xxx97xbr742o07t8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_intake_configurations
    ADD CONSTRAINT fkidbkptqw3xxx97xbr742o07t8 FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: course_unit_placements fkidvct6x9627l9jafaiw8jpbtl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unit_placements
    ADD CONSTRAINT fkidvct6x9627l9jafaiw8jpbtl FOREIGN KEY (effective_to_intake_id) REFERENCES public.intakes(id);

--
-- Name: units fklhny6bb2wuy9n1jnk07nry9d7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT fklhny6bb2wuy9n1jnk07nry9d7 FOREIGN KEY (department_id) REFERENCES public.departments(id);

--
-- Name: application_documents fkmn7jx61bon49nk5y29jp5hu5n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_documents
    ADD CONSTRAINT fkmn7jx61bon49nk5y29jp5hu5n FOREIGN KEY (application_id) REFERENCES public.applications(id);

--
-- Name: course_academic_periods fknxfw1fgvmh6vfd4n9xkohts52; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_academic_periods
    ADD CONSTRAINT fknxfw1fgvmh6vfd4n9xkohts52 FOREIGN KEY (academic_period_id) REFERENCES public.academic_periods(id);

--
-- Name: intake_courses fkp0q8r31e1tp9n6pfh93qjere8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intake_courses
    ADD CONSTRAINT fkp0q8r31e1tp9n6pfh93qjere8 FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: course_intake_configurations fkq39yecieg17jpgxbhheotikbq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_intake_configurations
    ADD CONSTRAINT fkq39yecieg17jpgxbhheotikbq FOREIGN KEY (intake_id) REFERENCES public.intakes(id);

--
-- Name: course_unit_placements fkqjhku5xe6t0o3chs5u5ysdums; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unit_placements
    ADD CONSTRAINT fkqjhku5xe6t0o3chs5u5ysdums FOREIGN KEY (effective_from_intake_id) REFERENCES public.intakes(id);

--
-- Name: intake_courses fkrfwt13jhlwosua1o49yw9ya6h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intake_courses
    ADD CONSTRAINT fkrfwt13jhlwosua1o49yw9ya6h FOREIGN KEY (intake_id) REFERENCES public.intakes(id);

--
-- Name: intakes fkrvnduaxbnr4we4oumwkuudcep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intakes
    ADD CONSTRAINT fkrvnduaxbnr4we4oumwkuudcep FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: courses fksv2mdywju86wq12x4did4xd78; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fksv2mdywju86wq12x4did4xd78 FOREIGN KEY (department_id) REFERENCES public.departments(id);

