-- V3: enrollments, fees, payments, ledger and finance jobs

--
-- Name: debit_claim_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.debit_claim_batches (
    id bigint NOT NULL,
    category character varying(30) NOT NULL,
    completed_at timestamp(6) without time zone,
    confirmed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    failed_rows integer NOT NULL,
    last_error character varying(1000),
    processed_rows integer NOT NULL,
    reason character varying(255) NOT NULL,
    result_url character varying(1000),
    source_url character varying(1000) NOT NULL,
    status character varying(25) NOT NULL,
    successful_rows integer NOT NULL,
    title character varying(160) NOT NULL,
    total_amount numeric(14,2) NOT NULL,
    total_rows integer NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    confirmed_by bigint,
    created_by bigint NOT NULL
);

--
-- Name: debit_claim_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.debit_claim_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.debit_claim_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: enrollments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enrollments (
    id bigint NOT NULL,
    admission_date date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    course_id bigint NOT NULL,
    current_academic_year_id bigint NOT NULL,
    current_course_academic_period_id bigint NOT NULL,
    enrolled_academic_year_id bigint NOT NULL,
    fee_structure_id bigint,
    intake_id bigint NOT NULL,
    student_id bigint NOT NULL,
    department_id bigint NOT NULL,
    CONSTRAINT enrollments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DEFERRED'::character varying, 'GRADUATED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);

--
-- Name: enrollments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enrollments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: fee_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_items (
    id bigint NOT NULL,
    active boolean NOT NULL,
    category character varying(100),
    code character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL
);

--
-- Name: fee_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: fee_ledger; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_ledger (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    credit numeric(12,2) NOT NULL,
    debit numeric(12,2) NOT NULL,
    description character varying(255) NOT NULL,
    document_number character varying(40) NOT NULL,
    external_reference character varying(100),
    posting_date date NOT NULL,
    status character varying(20) NOT NULL,
    transaction_type character varying(30) NOT NULL,
    course_academic_period_id bigint,
    created_by bigint,
    fee_structure_id bigint,
    payment_id bigint,
    reversal_of_id bigint,
    student_id bigint NOT NULL,
    CONSTRAINT fee_ledger_status_check CHECK (((status)::text = ANY ((ARRAY['POSTED'::character varying, 'REVERSED'::character varying])::text[]))),
    CONSTRAINT fee_ledger_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['TUITION_BILL'::character varying, 'ACCOMMODATION_BILL'::character varying, 'PENALTY_FEE'::character varying, 'PAYMENT_MPESA'::character varying, 'PAYMENT_BANK'::character varying, 'BURSARY_ALLOCATION'::character varying, 'FEE_WAIVER'::character varying, 'FEES_INVOICE'::character varying, 'RESIT_FEE'::character varying, 'RETAKE_FEE'::character varying, 'GRADUATION_FEE'::character varying, 'MANUAL_DEBIT'::character varying, 'SPONSOR_CREDIT'::character varying, 'LOAN_CREDIT'::character varying, 'MANUAL_CREDIT'::character varying, 'REVERSAL'::character varying, 'MIGRATION_OPENING_DEBIT'::character varying, 'MIGRATION_OPENING_CREDIT'::character varying])::text[])))
);

--
-- Name: fee_ledger_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_ledger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: fee_structure_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_structure_items (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    name character varying(150) NOT NULL,
    academic_period_id bigint NOT NULL,
    fee_structure_id bigint NOT NULL
);

--
-- Name: fee_structure_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_structure_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_structure_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: fee_structure_items_two; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_structure_items_two (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    name character varying(150) NOT NULL,
    fee_structure_id bigint NOT NULL
);

--
-- Name: fee_structure_items_two_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_structure_items_two ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_structure_items_two_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: fee_structures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_structures (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    academic_year_id bigint NOT NULL,
    copied_from_id bigint,
    course_id bigint NOT NULL,
    intake_id bigint NOT NULL
);

--
-- Name: fee_structures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_structures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_structures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: fee_structures_two; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_structures_two (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    academic_year_id bigint NOT NULL,
    course_id bigint NOT NULL,
    course_academic_period_id bigint NOT NULL,
    intake_id bigint NOT NULL
);

--
-- Name: fee_structures_two_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_structures_two ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_structures_two_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: finance_document_number_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.finance_document_number_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 20;

--
-- Name: SEQUENCE finance_document_number_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE public.finance_document_number_seq IS 'Generates numeric identifiers for finance documents such as invoices and credit/debit notes.';

--
-- Name: finance_receipt_number_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.finance_receipt_number_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 20;

--
-- Name: SEQUENCE finance_receipt_number_seq; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON SEQUENCE public.finance_receipt_number_seq IS 'Generates numeric identifiers for official student payment receipts.';

--
-- Name: graduation_fee_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.graduation_fee_items (
    id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    mandatory boolean NOT NULL,
    qualification_type character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    version bigint NOT NULL,
    effective_from_intake_sequence bigint NOT NULL,
    effective_to_intake_sequence bigint,
    fee_item_id bigint NOT NULL,
    CONSTRAINT graduation_fee_items_check CHECK (((amount >= (0)::numeric) AND ((effective_to_intake_sequence IS NULL) OR (effective_to_intake_sequence > effective_from_intake_sequence)))),
    CONSTRAINT graduation_fee_items_qualification_type_check CHECK (((qualification_type)::text = ANY ((ARRAY['CERTIFICATE'::character varying, 'DIPLOMA'::character varying, 'BACHELOR'::character varying, 'MASTERS'::character varying, 'PHD'::character varying])::text[])))
);

--
-- Name: graduation_fee_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.graduation_fee_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.graduation_fee_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: institution_finance_configuration; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.institution_finance_configuration (
    id bigint NOT NULL,
    account_reference_instructions character varying(200),
    bank_account_name character varying(150),
    bank_account_number character varying(80),
    bank_branch character varying(120),
    bank_name character varying(120),
    paybill_short_code character varying(20),
    updated_at timestamp(6) without time zone NOT NULL,
    version bigint NOT NULL
);

--
-- Name: mpesa_payment_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mpesa_payment_events (
    id bigint NOT NULL,
    account_reference character varying(80) NOT NULL,
    amount numeric(12,2) NOT NULL,
    attempt_count integer NOT NULL,
    business_short_code character varying(20) NOT NULL,
    failure_code character varying(50),
    failure_detail character varying(500),
    invoice_number character varying(80),
    next_attempt_at timestamp(6) without time zone NOT NULL,
    phone_hash character varying(64),
    phone_last_four character varying(4),
    processed_at timestamp(6) without time zone,
    processing_started_at timestamp(6) without time zone,
    received_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    third_party_transaction_id character varying(80),
    transaction_id character varying(40) NOT NULL,
    transaction_time timestamp(6) without time zone NOT NULL,
    transaction_type character varying(40),
    payment_id bigint,
    CONSTRAINT mpesa_payment_events_status_check CHECK (((status)::text = ANY ((ARRAY['RECEIVED'::character varying, 'PROCESSING'::character varying, 'PROCESSED'::character varying, 'RETRY'::character varying, 'REVIEW'::character varying, 'REJECTED'::character varying])::text[])))
);

--
-- Name: mpesa_payment_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mpesa_payment_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mpesa_payment_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: mpesa_stk_push_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mpesa_stk_push_requests (
    id bigint NOT NULL,
    account_reference character varying(80) NOT NULL,
    amount numeric(12,2) NOT NULL,
    callback_received_at timestamp(6) without time zone,
    checkout_request_id character varying(100),
    customer_message character varying(255),
    idempotency_key uuid NOT NULL,
    merchant_request_id character varying(100),
    mpesa_receipt_number character varying(40),
    phone_hash character varying(64) NOT NULL,
    phone_last_four character varying(4) NOT NULL,
    requested_at timestamp(6) without time zone NOT NULL,
    response_code character varying(30),
    response_description character varying(255),
    result_code integer,
    result_description character varying(500),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    course_academic_period_id bigint,
    student_id bigint NOT NULL,
    CONSTRAINT mpesa_stk_push_requests_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);

--
-- Name: mpesa_stk_push_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mpesa_stk_push_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mpesa_stk_push_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    gateway_reference character varying(100) NOT NULL,
    paid_at timestamp(6) without time zone NOT NULL,
    payer_name character varying(160),
    payer_type character varying(30) NOT NULL,
    payment_method character varying(30) NOT NULL,
    receipt_number character varying(50),
    remarks character varying(255),
    status character varying(255) NOT NULL,
    applied_course_academic_period_id bigint,
    recorded_by bigint,
    student_id bigint NOT NULL,
    CONSTRAINT payments_payer_type_check CHECK (((payer_type)::text = ANY ((ARRAY['STUDENT'::character varying, 'SPONSOR'::character varying, 'GOVERNMENT_LOAN'::character varying, 'BURSARY_PROVIDER'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying, 'REVERSED'::character varying])::text[])))
);

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: period_fee_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.period_fee_items (
    id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    mandatory boolean NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    version bigint NOT NULL,
    course_academic_period_id bigint NOT NULL,
    effective_from_intake_sequence bigint NOT NULL,
    effective_to_intake_sequence bigint,
    fee_item_id bigint NOT NULL,
    CONSTRAINT period_fee_items_check CHECK (((amount >= (0)::numeric) AND ((effective_to_intake_sequence IS NULL) OR (effective_to_intake_sequence > effective_from_intake_sequence))))
);

--
-- Name: period_fee_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.period_fee_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.period_fee_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: promotion_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promotion_jobs (
    id bigint NOT NULL,
    attempt_count integer NOT NULL,
    batch_id uuid NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    enrollment_id bigint NOT NULL,
    last_error character varying(1000),
    locked_at timestamp(6) without time zone,
    max_attempts integer NOT NULL,
    next_attempt_at timestamp(6) without time zone NOT NULL,
    skip_reason character varying(255),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

--
-- Name: promotion_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.promotion_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotion_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: debit_claim_batches debit_claim_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.debit_claim_batches
    ADD CONSTRAINT debit_claim_batches_pkey PRIMARY KEY (id);

--
-- Name: enrollments enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT enrollments_pkey PRIMARY KEY (id);

--
-- Name: fee_items fee_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_items
    ADD CONSTRAINT fee_items_pkey PRIMARY KEY (id);

--
-- Name: fee_ledger fee_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_ledger
    ADD CONSTRAINT fee_ledger_pkey PRIMARY KEY (id);

--
-- Name: fee_structure_items fee_structure_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure_items
    ADD CONSTRAINT fee_structure_items_pkey PRIMARY KEY (id);

--
-- Name: fee_structure_items_two fee_structure_items_two_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure_items_two
    ADD CONSTRAINT fee_structure_items_two_pkey PRIMARY KEY (id);

--
-- Name: fee_structures fee_structures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures
    ADD CONSTRAINT fee_structures_pkey PRIMARY KEY (id);

--
-- Name: fee_structures_two fee_structures_two_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures_two
    ADD CONSTRAINT fee_structures_two_pkey PRIMARY KEY (id);

--
-- Name: graduation_fee_items graduation_fee_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_fee_items
    ADD CONSTRAINT graduation_fee_items_pkey PRIMARY KEY (id);

--
-- Name: institution_finance_configuration institution_finance_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.institution_finance_configuration
    ADD CONSTRAINT institution_finance_configuration_pkey PRIMARY KEY (id);

--
-- Name: mpesa_payment_events mpesa_payment_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mpesa_payment_events
    ADD CONSTRAINT mpesa_payment_events_pkey PRIMARY KEY (id);

--
-- Name: mpesa_stk_push_requests mpesa_stk_push_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mpesa_stk_push_requests
    ADD CONSTRAINT mpesa_stk_push_requests_pkey PRIMARY KEY (id);

--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

--
-- Name: period_fee_items period_fee_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.period_fee_items
    ADD CONSTRAINT period_fee_items_pkey PRIMARY KEY (id);

--
-- Name: promotion_jobs promotion_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotion_jobs
    ADD CONSTRAINT promotion_jobs_pkey PRIMARY KEY (id);

--
-- Name: mpesa_stk_push_requests uk45mvjfrj4mkjt21dxy4hel6ri; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mpesa_stk_push_requests
    ADD CONSTRAINT uk45mvjfrj4mkjt21dxy4hel6ri UNIQUE (idempotency_key);

--
-- Name: debit_claim_batches uk9s6pfdr6fkr9tg3oan6i4pv4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.debit_claim_batches
    ADD CONSTRAINT uk9s6pfdr6fkr9tg3oan6i4pv4 UNIQUE (uuid);

--
-- Name: fee_structures_two uk_fee_structures_two_cohort_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures_two
    ADD CONSTRAINT uk_fee_structures_two_cohort_period UNIQUE (course_id, academic_year_id, intake_id, course_academic_period_id);

--
-- Name: payments uk_payment_reference; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk_payment_reference UNIQUE (gateway_reference);

--
-- Name: mpesa_stk_push_requests uklctci0dcxqtkfms1qmxe6yie2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mpesa_stk_push_requests
    ADD CONSTRAINT uklctci0dcxqtkfms1qmxe6yie2 UNIQUE (checkout_request_id);

--
-- Name: fee_ledger ukns5p26xx8jk590rmkmy74qrxu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_ledger
    ADD CONSTRAINT ukns5p26xx8jk590rmkmy74qrxu UNIQUE (document_number);

--
-- Name: fee_ledger ukobhcvxyl414vllh1hsxxkqax8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_ledger
    ADD CONSTRAINT ukobhcvxyl414vllh1hsxxkqax8 UNIQUE (reversal_of_id);

--
-- Name: mpesa_stk_push_requests ukqcny8tm88yk3hm0h0w5s0je7k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mpesa_stk_push_requests
    ADD CONSTRAINT ukqcny8tm88yk3hm0h0w5s0je7k UNIQUE (uuid);

--
-- Name: payments uku6rnuxne864s4rh7qgeql1vx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uku6rnuxne864s4rh7qgeql1vx UNIQUE (receipt_number);

--
-- Name: fee_items uq_fee_items_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_items
    ADD CONSTRAINT uq_fee_items_code UNIQUE (code);

--
-- Name: fee_items uq_fee_items_uuid; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_items
    ADD CONSTRAINT uq_fee_items_uuid UNIQUE (uuid);

--
-- Name: graduation_fee_items uq_graduation_fee_item_start; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_fee_items
    ADD CONSTRAINT uq_graduation_fee_item_start UNIQUE (qualification_type, fee_item_id, effective_from_intake_sequence);

--
-- Name: period_fee_items uq_period_fee_item_start; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.period_fee_items
    ADD CONSTRAINT uq_period_fee_item_start UNIQUE (course_academic_period_id, fee_item_id, effective_from_intake_sequence);

--
-- Name: idx_debit_claim_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_debit_claim_status ON public.debit_claim_batches USING btree (status, created_at);

--
-- Name: idx_fee_ledger_student; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fee_ledger_student ON public.fee_ledger USING btree (student_id);

--
-- Name: idx_graduation_fee_effective; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_graduation_fee_effective ON public.graduation_fee_items USING btree (qualification_type, effective_from_intake_sequence, effective_to_intake_sequence);

--
-- Name: idx_period_fee_items_course_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_period_fee_items_course_period ON public.period_fee_items USING btree (course_academic_period_id);

--
-- Name: idx_period_fee_items_effective_range; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_period_fee_items_effective_range ON public.period_fee_items USING btree (course_academic_period_id, effective_from_intake_sequence, effective_to_intake_sequence);

--
-- Name: idx_period_fee_items_period_fee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_period_fee_items_period_fee ON public.period_fee_items USING btree (course_academic_period_id, fee_item_id);

--
-- Name: fee_structures_two fk1a1mipxij0wr3fxt4bsr0rrn4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures_two
    ADD CONSTRAINT fk1a1mipxij0wr3fxt4bsr0rrn4 FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: fee_structures_two fk30yypt8dqvkl8b9yi3nvrvfvw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures_two
    ADD CONSTRAINT fk30yypt8dqvkl8b9yi3nvrvfvw FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: fee_structures fk3dbckl1fhwec5u366wj09wunm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures
    ADD CONSTRAINT fk3dbckl1fhwec5u366wj09wunm FOREIGN KEY (intake_id) REFERENCES public.intakes(id);

--
-- Name: mpesa_payment_events fk3yljr4ko698m8y39yh7hkm3sa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mpesa_payment_events
    ADD CONSTRAINT fk3yljr4ko698m8y39yh7hkm3sa FOREIGN KEY (payment_id) REFERENCES public.payments(id);

--
-- Name: enrollments fk64fmvl8dbbdmf2ca1iq6fj0fl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk64fmvl8dbbdmf2ca1iq6fj0fl FOREIGN KEY (current_course_academic_period_id) REFERENCES public.course_academic_periods(id);

--
-- Name: payments fk6ooq278k2bs5xi8t5o6oort1v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk6ooq278k2bs5xi8t5o6oort1v FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: enrollments fk7c6s4fg4xgqe0tsek3o53qkmq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk7c6s4fg4xgqe0tsek3o53qkmq FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures(id);

--
-- Name: debit_claim_batches fk7r51rbov9wfrlfenmnuos850a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.debit_claim_batches
    ADD CONSTRAINT fk7r51rbov9wfrlfenmnuos850a FOREIGN KEY (confirmed_by) REFERENCES public.users(id);

--
-- Name: enrollments fk8kf1u1857xgo56xbfmnif2c51; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk8kf1u1857xgo56xbfmnif2c51 FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: period_fee_items fk_period_fee_item_course_period; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.period_fee_items
    ADD CONSTRAINT fk_period_fee_item_course_period FOREIGN KEY (course_academic_period_id) REFERENCES public.course_academic_periods(id);

--
-- Name: period_fee_items fk_period_fee_item_fee_item; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.period_fee_items
    ADD CONSTRAINT fk_period_fee_item_fee_item FOREIGN KEY (fee_item_id) REFERENCES public.fee_items(id);

--
-- Name: period_fee_items fk_period_fee_item_from_intake; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.period_fee_items
    ADD CONSTRAINT fk_period_fee_item_from_intake FOREIGN KEY (effective_from_intake_sequence) REFERENCES public.intakes(sequence_number);

--
-- Name: period_fee_items fk_period_fee_item_to_intake; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.period_fee_items
    ADD CONSTRAINT fk_period_fee_item_to_intake FOREIGN KEY (effective_to_intake_sequence) REFERENCES public.intakes(sequence_number);

--
-- Name: payments fka6nye1mj985yt9mg3umq45fnq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fka6nye1mj985yt9mg3umq45fnq FOREIGN KEY (recorded_by) REFERENCES public.users(id);

--
-- Name: enrollments fkah89706go4j8m91dr5e1ta0jm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkah89706go4j8m91dr5e1ta0jm FOREIGN KEY (intake_id) REFERENCES public.intakes(id);

--
-- Name: fee_structure_items fkakxlmly7887yhod9l2wgapc0e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure_items
    ADD CONSTRAINT fkakxlmly7887yhod9l2wgapc0e FOREIGN KEY (academic_period_id) REFERENCES public.academic_periods(id);

--
-- Name: fee_structures fkb2emuafexommm3bx0gvbp53x2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures
    ADD CONSTRAINT fkb2emuafexommm3bx0gvbp53x2 FOREIGN KEY (course_id) REFERENCES public.courses(id);

--
-- Name: fee_structure_items_two fkbw3qxeymg5qt27lpw3bppkjll; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure_items_two
    ADD CONSTRAINT fkbw3qxeymg5qt27lpw3bppkjll FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures_two(id);

--
-- Name: graduation_fee_items fke53j76e25bcopyq7q7i69c09e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_fee_items
    ADD CONSTRAINT fke53j76e25bcopyq7q7i69c09e FOREIGN KEY (fee_item_id) REFERENCES public.fee_items(id);

--
-- Name: enrollments fkeepr0cwd5a2bw310a12b2q7oi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkeepr0cwd5a2bw310a12b2q7oi FOREIGN KEY (current_academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: fee_structure_items fkfh6m8ifmycr1hkamdcjf6lmo8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure_items
    ADD CONSTRAINT fkfh6m8ifmycr1hkamdcjf6lmo8 FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures(id);

--
-- Name: fee_structures_two fkfv9hfwit167wh3xbp0mnqiwkb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures_two
    ADD CONSTRAINT fkfv9hfwit167wh3xbp0mnqiwkb FOREIGN KEY (intake_id) REFERENCES public.intakes(id);

--
-- Name: fee_structures fkgvda8q1mibfvp8wfptqk0dfiu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures
    ADD CONSTRAINT fkgvda8q1mibfvp8wfptqk0dfiu FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: fee_structures fkhf0ckxwvffcafus55gvt04cty; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures
    ADD CONSTRAINT fkhf0ckxwvffcafus55gvt04cty FOREIGN KEY (copied_from_id) REFERENCES public.fee_structures(id);

--
-- Name: fee_ledger fkhhl3spk4nnuplugedkj23jxto; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_ledger
    ADD CONSTRAINT fkhhl3spk4nnuplugedkj23jxto FOREIGN KEY (reversal_of_id) REFERENCES public.fee_ledger(id);

--
-- Name: mpesa_stk_push_requests fkhljxr6lgtdrfmuvpfw3blv4py; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mpesa_stk_push_requests
    ADD CONSTRAINT fkhljxr6lgtdrfmuvpfw3blv4py FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: graduation_fee_items fkhmv8lx0eto2qiv18qt4og17eu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_fee_items
    ADD CONSTRAINT fkhmv8lx0eto2qiv18qt4og17eu FOREIGN KEY (effective_to_intake_sequence) REFERENCES public.intakes(sequence_number);

--
-- Name: enrollments fkho8mcicp4196ebpltdn9wl6co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkho8mcicp4196ebpltdn9wl6co FOREIGN KEY (course_id) REFERENCES public.courses(id);

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk_enrollments_department FOREIGN KEY (department_id) REFERENCES public.departments(id);

CREATE INDEX idx_enrollments_department_id ON public.enrollments (department_id);

--
-- Name: fee_ledger fkke6nl5tuwje83bdak9um94lng; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_ledger
    ADD CONSTRAINT fkke6nl5tuwje83bdak9um94lng FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures(id);

--
-- Name: fee_ledger fkl80s3ldpphg6v3oa144hbspiy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_ledger
    ADD CONSTRAINT fkl80s3ldpphg6v3oa144hbspiy FOREIGN KEY (created_by) REFERENCES public.users(id);

--
-- Name: graduation_fee_items fklmla16hxbwctt1f1yhyg5ebpv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_fee_items
    ADD CONSTRAINT fklmla16hxbwctt1f1yhyg5ebpv FOREIGN KEY (effective_from_intake_sequence) REFERENCES public.intakes(sequence_number);

--
-- Name: enrollments fkm0ovbmrdpmss1gndptoin8drw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkm0ovbmrdpmss1gndptoin8drw FOREIGN KEY (enrolled_academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: mpesa_stk_push_requests fknt7rlwsjhg4m2o1f3546xb5av; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mpesa_stk_push_requests
    ADD CONSTRAINT fknt7rlwsjhg4m2o1f3546xb5av FOREIGN KEY (course_academic_period_id) REFERENCES public.course_academic_periods(id);

--
-- Name: fee_ledger fkntfkt7mngsue38emc7tocg2km; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_ledger
    ADD CONSTRAINT fkntfkt7mngsue38emc7tocg2km FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: fee_structures_two fkof6avoa2pt8ccqn9eejyl9sp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structures_two
    ADD CONSTRAINT fkof6avoa2pt8ccqn9eejyl9sp FOREIGN KEY (course_academic_period_id) REFERENCES public.course_academic_periods(id);

--
-- Name: debit_claim_batches fkonpxjtw31lt84ee6628tp0r6i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.debit_claim_batches
    ADD CONSTRAINT fkonpxjtw31lt84ee6628tp0r6i FOREIGN KEY (created_by) REFERENCES public.users(id);

--
-- Name: payments fkr0jysqcax78n065lv1622ddpd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkr0jysqcax78n065lv1622ddpd FOREIGN KEY (applied_course_academic_period_id) REFERENCES public.course_academic_periods(id);

--
-- Name: fee_ledger fkrer4u9g10wmo3h40co9aiyuj9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_ledger
    ADD CONSTRAINT fkrer4u9g10wmo3h40co9aiyuj9 FOREIGN KEY (course_academic_period_id) REFERENCES public.course_academic_periods(id);

--
-- Name: fee_ledger fksutq7y4us468x35fafq48mxj5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_ledger
    ADD CONSTRAINT fksutq7y4us468x35fafq48mxj5 FOREIGN KEY (payment_id) REFERENCES public.payments(id);

