-- V4: registrations, results, clearance, graduation and certificates

--
-- Name: academic_year_clearance_departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academic_year_clearance_departments (
    id bigint NOT NULL,
    display_order integer NOT NULL,
    academic_year_id bigint NOT NULL,
    department_id bigint NOT NULL
);

--
-- Name: academic_year_clearance_departments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.academic_year_clearance_departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_year_clearance_departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: certificate_generation_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.certificate_generation_jobs (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    error_message character varying(1000),
    failed_certificates integer NOT NULL,
    processed_certificates integer NOT NULL,
    requested_at timestamp(6) without time zone NOT NULL,
    started_at timestamp(6) without time zone,
    status character varying(40) NOT NULL,
    successful_certificates integer NOT NULL,
    total_certificates integer NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    graduation_batch_id bigint NOT NULL,
    requested_by bigint NOT NULL,
    CONSTRAINT certificate_generation_jobs_status_check CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'COMPLETED_WITH_ERRORS'::character varying, 'FAILED'::character varying])::text[])))
);

--
-- Name: certificate_generation_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.certificate_generation_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certificate_generation_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: clearance_applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clearance_applications (
    id bigint NOT NULL,
    applied_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone,
    status character varying(30) NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    enrollment_id bigint NOT NULL,
    academic_year_id bigint NOT NULL,
    CONSTRAINT clearance_applications_status_check CHECK (((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'IN_PROGRESS'::character varying, 'ACTION_REQUIRED'::character varying, 'CLEARED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])))
);

--
-- Name: clearance_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clearance_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clearance_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: clearance_checks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clearance_checks (
    id bigint NOT NULL,
    display_order integer NOT NULL,
    mandatory boolean NOT NULL,
    remarks character varying(1000),
    reviewed_at timestamp(6) without time zone,
    status character varying(30) NOT NULL,
    version bigint NOT NULL,
    application_id bigint NOT NULL,
    department_id bigint NOT NULL,
    reviewed_by bigint,
    CONSTRAINT clearance_checks_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CLEARED'::character varying, 'ACTION_REQUIRED'::character varying, 'REJECTED'::character varying])::text[])))
);

--
-- Name: clearance_checks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clearance_checks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clearance_checks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: exam_cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_cards (
    id bigint NOT NULL,
    issued_at timestamp(6) without time zone NOT NULL,
    verification_code uuid NOT NULL,
    course_academic_period_id bigint NOT NULL,
    student_id bigint NOT NULL
);

--
-- Name: exam_cards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: graduation_application_fee_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.graduation_application_fee_items (
    id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    display_order integer NOT NULL,
    fee_item_code character varying(50) NOT NULL,
    fee_item_name character varying(150) NOT NULL,
    fee_item_uuid uuid NOT NULL,
    application_id bigint NOT NULL
);

--
-- Name: graduation_application_fee_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.graduation_application_fee_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.graduation_application_fee_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: graduation_applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.graduation_applications (
    id bigint NOT NULL,
    applied_at timestamp(6) without time zone NOT NULL,
    status character varying(40) NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    version bigint NOT NULL,
    enrollment_id bigint NOT NULL,
    ledger_entry_id bigint,
    clearance_complete boolean,
    earned_credits integer,
    eligibility_assessed_at timestamp(6) without time zone,
    failed_units integer,
    missing_results integer,
    passed_units integer,
    required_credits integer,
    required_units integer,
    conferred_at timestamp(6) without time zone,
    graduation_date date,
    conferred_by bigint,
    graduation_batch_id bigint,
    CONSTRAINT graduation_applications_status_check CHECK (((status)::text = ANY ((ARRAY['APPLIED'::character varying, 'CLEARANCE_IN_PROGRESS'::character varying, 'READY_FOR_GRADUATION_REVIEW'::character varying, 'PENDING_GRADUATION'::character varying, 'GRADUATED'::character varying, 'REJECTED'::character varying])::text[])))
);

--
-- Name: graduation_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.graduation_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.graduation_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: graduation_batch_candidates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.graduation_batch_candidates (
    id bigint NOT NULL,
    failure_reason character varying(500),
    processed_at timestamp(6) without time zone,
    status character varying(30) NOT NULL,
    version bigint NOT NULL,
    graduation_application_id bigint NOT NULL,
    graduation_batch_id bigint NOT NULL,
    CONSTRAINT graduation_batch_candidates_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'GRADUATED'::character varying, 'SKIPPED'::character varying, 'FAILED'::character varying])::text[])))
);

--
-- Name: graduation_batch_candidates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.graduation_batch_candidates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.graduation_batch_candidates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: graduation_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.graduation_batches (
    id bigint NOT NULL,
    conferred_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    failed_candidates integer NOT NULL,
    graduation_date date NOT NULL,
    name character varying(150) NOT NULL,
    processed_candidates integer NOT NULL,
    status character varying(40) NOT NULL,
    successful_candidates integer NOT NULL,
    total_candidates integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    academic_year_id bigint NOT NULL,
    conferred_by bigint,
    created_by bigint NOT NULL,
    CONSTRAINT graduation_batches_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PROCESSING'::character varying, 'CONFERRED'::character varying, 'COMPLETED_WITH_ERRORS'::character varying])::text[])))
);

--
-- Name: graduation_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.graduation_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.graduation_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: graduation_certificates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.graduation_certificates (
    id bigint NOT NULL,
    admission_number character varying(80) NOT NULL,
    award_title character varying(180) NOT NULL,
    certificate_number character varying(60),
    checksum_sha256 character varying(64),
    course_code character varying(50) NOT NULL,
    course_name character varying(180) NOT NULL,
    error_message character varying(1000),
    file_size bigint,
    generated_at timestamp(6) without time zone,
    graduation_date date NOT NULL,
    status character varying(30) NOT NULL,
    storage_path character varying(500),
    student_name character varying(180) NOT NULL,
    uuid uuid NOT NULL,
    verification_code character varying(60) NOT NULL,
    version bigint NOT NULL,
    graduation_application_id bigint NOT NULL,
    generation_job_id bigint NOT NULL,
    storage_url character varying(1000),
    CONSTRAINT graduation_certificates_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'GENERATING'::character varying, 'GENERATED'::character varying, 'FAILED'::character varying])::text[])))
);

--
-- Name: graduation_certificates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.graduation_certificates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.graduation_certificates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: student_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_results (
    id bigint NOT NULL,
    approved_at timestamp(6) without time zone,
    ca_marks numeric(5,2),
    created_at timestamp(6) without time zone NOT NULL,
    exam_marks numeric(5,2),
    grade character varying(10),
    passed boolean NOT NULL,
    remarks text,
    status character varying(20) NOT NULL,
    total_marks numeric(5,2),
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    version bigint NOT NULL,
    approved_by_id bigint,
    recorded_by_id bigint,
    student_unit_registration_id bigint NOT NULL,
    CONSTRAINT student_results_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'APPROVED'::character varying, 'RELEASED'::character varying, 'WITHHELD'::character varying])::text[])))
);

--
-- Name: student_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: student_unit_registrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_unit_registrations (
    id bigint NOT NULL,
    attempt_type character varying(20) NOT NULL,
    registered_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    course_unit_placement_id bigint NOT NULL,
    enrollment_id bigint NOT NULL,
    CONSTRAINT student_unit_registrations_attempt_type_check CHECK (((attempt_type)::text = ANY ((ARRAY['NORMAL'::character varying, 'RETAKE'::character varying, 'SUPPLEMENTARY'::character varying, 'EXEMPTION'::character varying])::text[]))),
    CONSTRAINT student_unit_registrations_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DROPPED'::character varying, 'COMPLETED'::character varying])::text[])))
);

--
-- Name: student_unit_registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_unit_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_unit_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: academic_year_clearance_departments academic_year_clearance_departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_year_clearance_departments
    ADD CONSTRAINT academic_year_clearance_departments_pkey PRIMARY KEY (id);

--
-- Name: certificate_generation_jobs certificate_generation_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificate_generation_jobs
    ADD CONSTRAINT certificate_generation_jobs_pkey PRIMARY KEY (id);

--
-- Name: clearance_applications clearance_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_applications
    ADD CONSTRAINT clearance_applications_pkey PRIMARY KEY (id);

--
-- Name: clearance_checks clearance_checks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_checks
    ADD CONSTRAINT clearance_checks_pkey PRIMARY KEY (id);

--
-- Name: exam_cards exam_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_cards
    ADD CONSTRAINT exam_cards_pkey PRIMARY KEY (id);

--
-- Name: graduation_application_fee_items graduation_application_fee_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_application_fee_items
    ADD CONSTRAINT graduation_application_fee_items_pkey PRIMARY KEY (id);

--
-- Name: graduation_applications graduation_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_applications
    ADD CONSTRAINT graduation_applications_pkey PRIMARY KEY (id);

--
-- Name: graduation_batch_candidates graduation_batch_candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_batch_candidates
    ADD CONSTRAINT graduation_batch_candidates_pkey PRIMARY KEY (id);

--
-- Name: graduation_batches graduation_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_batches
    ADD CONSTRAINT graduation_batches_pkey PRIMARY KEY (id);

--
-- Name: graduation_certificates graduation_certificates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_certificates
    ADD CONSTRAINT graduation_certificates_pkey PRIMARY KEY (id);

--
-- Name: student_results student_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_results
    ADD CONSTRAINT student_results_pkey PRIMARY KEY (id);

--
-- Name: student_unit_registrations student_unit_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_unit_registrations
    ADD CONSTRAINT student_unit_registrations_pkey PRIMARY KEY (id);

--
-- Name: student_results uk3rbsijfg4h0tcbbe6un23ip00; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_results
    ADD CONSTRAINT uk3rbsijfg4h0tcbbe6un23ip00 UNIQUE (uuid);

--
-- Name: graduation_batches uk7npj68ykd7qlswqp3vmoua0ld; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_batches
    ADD CONSTRAINT uk7npj68ykd7qlswqp3vmoua0ld UNIQUE (uuid);

--
-- Name: graduation_certificates uk9jl3khokc6mtgv7b418f25w6j; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_certificates
    ADD CONSTRAINT uk9jl3khokc6mtgv7b418f25w6j UNIQUE (uuid);

--
-- Name: exam_cards uk_exam_card_student_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_cards
    ADD CONSTRAINT uk_exam_card_student_period UNIQUE (student_id, course_academic_period_id);

--
-- Name: student_results ukii4vkjj5wtbs662lpalw4rjui; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_results
    ADD CONSTRAINT ukii4vkjj5wtbs662lpalw4rjui UNIQUE (student_unit_registration_id);

--
-- Name: graduation_applications ukkeml8vmmyuhv85foxp8061q4q; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_applications
    ADD CONSTRAINT ukkeml8vmmyuhv85foxp8061q4q UNIQUE (ledger_entry_id);

--
-- Name: clearance_applications ukmlk7bmdkq7bhxnacg8ma1hm8a; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_applications
    ADD CONSTRAINT ukmlk7bmdkq7bhxnacg8ma1hm8a UNIQUE (uuid);

--
-- Name: graduation_certificates ukp4j0sqh8shmh72qn08gnkmuvl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_certificates
    ADD CONSTRAINT ukp4j0sqh8shmh72qn08gnkmuvl UNIQUE (verification_code);

--
-- Name: certificate_generation_jobs ukq672hf2eukumwih043jaqdwna; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificate_generation_jobs
    ADD CONSTRAINT ukq672hf2eukumwih043jaqdwna UNIQUE (uuid);

--
-- Name: exam_cards ukyqxly282vfxcdbpe332f1j6p; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_cards
    ADD CONSTRAINT ukyqxly282vfxcdbpe332f1j6p UNIQUE (verification_code);

--
-- Name: graduation_certificates uq_certificate_application; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_certificates
    ADD CONSTRAINT uq_certificate_application UNIQUE (graduation_application_id);

--
-- Name: certificate_generation_jobs uq_certificate_job_batch; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificate_generation_jobs
    ADD CONSTRAINT uq_certificate_job_batch UNIQUE (graduation_batch_id);

--
-- Name: graduation_certificates uq_certificate_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_certificates
    ADD CONSTRAINT uq_certificate_number UNIQUE (certificate_number);

--
-- Name: clearance_applications uq_clearance_application_enrollment_year; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_applications
    ADD CONSTRAINT uq_clearance_application_enrollment_year UNIQUE (enrollment_id, academic_year_id);

--
-- Name: clearance_checks uq_clearance_check_application_department; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_checks
    ADD CONSTRAINT uq_clearance_check_application_department UNIQUE (application_id, department_id);

--
-- Name: graduation_applications uq_graduation_application_enrollment; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_applications
    ADD CONSTRAINT uq_graduation_application_enrollment UNIQUE (enrollment_id);

--
-- Name: graduation_batch_candidates uq_graduation_batch_candidate; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_batch_candidates
    ADD CONSTRAINT uq_graduation_batch_candidate UNIQUE (graduation_batch_id, graduation_application_id);

--
-- Name: academic_year_clearance_departments uq_year_clearance_department; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_year_clearance_departments
    ADD CONSTRAINT uq_year_clearance_department UNIQUE (academic_year_id, department_id);

--
-- Name: idx_student_results_approved_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_student_results_approved_by ON public.student_results USING btree (approved_by_id);

--
-- Name: idx_student_results_recorded_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_student_results_recorded_by ON public.student_results USING btree (recorded_by_id);

--
-- Name: idx_student_results_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_student_results_status ON public.student_results USING btree (status);

--
-- Name: graduation_applications fk1u3v526x6gwfbdylwcj4vvtdf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_applications
    ADD CONSTRAINT fk1u3v526x6gwfbdylwcj4vvtdf FOREIGN KEY (graduation_batch_id) REFERENCES public.graduation_batches(id);

--
-- Name: student_results fk1y0jcgl31l4vmitwmvinfucv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_results
    ADD CONSTRAINT fk1y0jcgl31l4vmitwmvinfucv FOREIGN KEY (student_unit_registration_id) REFERENCES public.student_unit_registrations(id);

--
-- Name: graduation_applications fk2g3e1sjhr86bxleaa8o6w72f9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_applications
    ADD CONSTRAINT fk2g3e1sjhr86bxleaa8o6w72f9 FOREIGN KEY (conferred_by) REFERENCES public.users(id);

--
-- Name: exam_cards fk5nx5fvhw2raqg8s1msn1uvus5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_cards
    ADD CONSTRAINT fk5nx5fvhw2raqg8s1msn1uvus5 FOREIGN KEY (student_id) REFERENCES public.students(id);

--
-- Name: clearance_checks fk6pih99w7c7vth6x25qbe3xb5a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_checks
    ADD CONSTRAINT fk6pih99w7c7vth6x25qbe3xb5a FOREIGN KEY (department_id) REFERENCES public.departments(id);

--
-- Name: academic_year_clearance_departments fk99ie6rrpo4y8637nt4t6m2q3x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_year_clearance_departments
    ADD CONSTRAINT fk99ie6rrpo4y8637nt4t6m2q3x FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: clearance_checks fkargwy5th1ak5488w19j9kgood; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_checks
    ADD CONSTRAINT fkargwy5th1ak5488w19j9kgood FOREIGN KEY (reviewed_by) REFERENCES public.users(id);

--
-- Name: graduation_certificates fkbo0qssyk5b2jvkrf8o8ase3df; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_certificates
    ADD CONSTRAINT fkbo0qssyk5b2jvkrf8o8ase3df FOREIGN KEY (graduation_application_id) REFERENCES public.graduation_applications(id);

--
-- Name: exam_cards fkdejuxlme15i242fx38y3ellq5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_cards
    ADD CONSTRAINT fkdejuxlme15i242fx38y3ellq5 FOREIGN KEY (course_academic_period_id) REFERENCES public.course_academic_periods(id);

--
-- Name: graduation_batch_candidates fke991y6whgypw4vi6uiw37u0pa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_batch_candidates
    ADD CONSTRAINT fke991y6whgypw4vi6uiw37u0pa FOREIGN KEY (graduation_batch_id) REFERENCES public.graduation_batches(id);

--
-- Name: student_unit_registrations fkeat1j6ork9kscxt2ki9faorrl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_unit_registrations
    ADD CONSTRAINT fkeat1j6ork9kscxt2ki9faorrl FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id);

--
-- Name: student_results fkgdgboixd0tkfrqqwj8xk0qryi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_results
    ADD CONSTRAINT fkgdgboixd0tkfrqqwj8xk0qryi FOREIGN KEY (recorded_by_id) REFERENCES public.users(id);

--
-- Name: student_unit_registrations fkh40b4mb463am0h6t8pcw1e0w0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_unit_registrations
    ADD CONSTRAINT fkh40b4mb463am0h6t8pcw1e0w0 FOREIGN KEY (course_unit_placement_id) REFERENCES public.course_unit_placements(id);

--
-- Name: certificate_generation_jobs fkkofakk0vje94esloh14eyme4k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificate_generation_jobs
    ADD CONSTRAINT fkkofakk0vje94esloh14eyme4k FOREIGN KEY (graduation_batch_id) REFERENCES public.graduation_batches(id);

--
-- Name: graduation_batch_candidates fklpd1ty612eggj841cqe7whm3q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_batch_candidates
    ADD CONSTRAINT fklpd1ty612eggj841cqe7whm3q FOREIGN KEY (graduation_application_id) REFERENCES public.graduation_applications(id);

--
-- Name: student_results fkm42rdt9bqr76e9xji8y0vvtjj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_results
    ADD CONSTRAINT fkm42rdt9bqr76e9xji8y0vvtjj FOREIGN KEY (approved_by_id) REFERENCES public.users(id);

--
-- Name: graduation_batches fkmfl6tjv8gcv90om56mt3b4bvh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_batches
    ADD CONSTRAINT fkmfl6tjv8gcv90om56mt3b4bvh FOREIGN KEY (created_by) REFERENCES public.users(id);

--
-- Name: graduation_applications fkncq0fesesu3mydl0ufkn1hvpw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_applications
    ADD CONSTRAINT fkncq0fesesu3mydl0ufkn1hvpw FOREIGN KEY (ledger_entry_id) REFERENCES public.fee_ledger(id);

--
-- Name: graduation_application_fee_items fknjpum7iv0sw28s41gulqxfneh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_application_fee_items
    ADD CONSTRAINT fknjpum7iv0sw28s41gulqxfneh FOREIGN KEY (application_id) REFERENCES public.graduation_applications(id);

--
-- Name: certificate_generation_jobs fkodsa0nncqfwbxpssdx01mjdn6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificate_generation_jobs
    ADD CONSTRAINT fkodsa0nncqfwbxpssdx01mjdn6 FOREIGN KEY (requested_by) REFERENCES public.users(id);

--
-- Name: clearance_applications fkpj35tvi2s0ux7xi8vw7pvsgot; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_applications
    ADD CONSTRAINT fkpj35tvi2s0ux7xi8vw7pvsgot FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: graduation_applications fkpu8h3rkdsx56my49aesuh1ui1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_applications
    ADD CONSTRAINT fkpu8h3rkdsx56my49aesuh1ui1 FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id);

--
-- Name: academic_year_clearance_departments fkqn1okmi2twwp1v6ymbu985ugf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_year_clearance_departments
    ADD CONSTRAINT fkqn1okmi2twwp1v6ymbu985ugf FOREIGN KEY (department_id) REFERENCES public.departments(id);

--
-- Name: graduation_batches fkr0f9hh01hvk8qpy7fftjdhpxk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_batches
    ADD CONSTRAINT fkr0f9hh01hvk8qpy7fftjdhpxk FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);

--
-- Name: clearance_checks fkrfutuou4mrkyqb0gtovm8aopg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_checks
    ADD CONSTRAINT fkrfutuou4mrkyqb0gtovm8aopg FOREIGN KEY (application_id) REFERENCES public.clearance_applications(id);

--
-- Name: graduation_certificates fkrjkqttc5sr6100boy5viv8ikd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_certificates
    ADD CONSTRAINT fkrjkqttc5sr6100boy5viv8ikd FOREIGN KEY (generation_job_id) REFERENCES public.certificate_generation_jobs(id);

--
-- Name: clearance_applications fks0dy8greci1bualk9cn7662gy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clearance_applications
    ADD CONSTRAINT fks0dy8greci1bualk9cn7662gy FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id);

--
-- Name: graduation_batches fksfsf0klxl56n00ysmmuu4wfen; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_batches
    ADD CONSTRAINT fksfsf0klxl56n00ysmmuu4wfen FOREIGN KEY (conferred_by) REFERENCES public.users(id);



-- Consolidated from V7__add_registration_origin_to_student_unit_registrations.sql

-- Add registration origin support for legacy/current registration tracking
ALTER TABLE public.student_unit_registrations
    ADD COLUMN IF NOT EXISTS registration_origin varchar(20);

UPDATE public.student_unit_registrations
SET registration_origin = 'CURRENT'
WHERE registration_origin IS NULL;

ALTER TABLE public.student_unit_registrations
    ALTER COLUMN registration_origin SET DEFAULT 'CURRENT';

ALTER TABLE public.student_unit_registrations
    ALTER COLUMN registration_origin SET NOT NULL;



-- Consolidated from V8__add_graduation_award_snapshot.sql

-- ============================================================================
-- V7: Finalize graduation application award and academic approval fields
-- ============================================================================
--
-- Application time:
--   - award_title is stored
--   - qualification_type is stored
--   - final_cumulative_average remains NULL
--   - award_classification remains NULL
--
-- Approval time:
--   - final_cumulative_average is calculated and stored
--   - award_classification is calculated and stored
--   - academic_approval_by is stored
--   - academic_approved_at is stored
--
-- The migration is data-preserving for existing graduation applications.
-- ============================================================================


-- ============================================================================
-- 1. ADD NEW COLUMNS AS NULLABLE
-- ============================================================================
--
-- Award fields are temporarily nullable so existing applications can be
-- backfilled before NOT NULL is enforced.

ALTER TABLE public.graduation_applications
    ADD COLUMN award_title VARCHAR(200),
    ADD COLUMN qualification_type VARCHAR(50),
    ADD COLUMN final_cumulative_average NUMERIC(5, 2),
    ADD COLUMN award_classification VARCHAR(80),
    ADD COLUMN academic_approval_by BIGINT,
    ADD COLUMN academic_approved_at TIMESTAMPTZ;


-- ============================================================================
-- 2. BACKFILL AWARD INFORMATION FOR EXISTING APPLICATIONS
-- ============================================================================
--
-- Relationship:
--
-- graduation_applications
--      -> enrollments
--          -> courses
--
-- The award title and qualification type are copied from the course.

UPDATE public.graduation_applications graduation_application
SET
    award_title = BTRIM(course.award_title),
    qualification_type = course.qualification_type
    FROM public.enrollments enrollment
JOIN public.courses course
ON course.id = enrollment.course_id
WHERE graduation_application.enrollment_id = enrollment.id
  AND course.award_title IS NOT NULL
  AND BTRIM(course.award_title) <> ''
  AND course.qualification_type IS NOT NULL;


-- ============================================================================
-- 3. VERIFY EXISTING APPLICATIONS
-- ============================================================================
--
-- Stop the migration rather than guessing an official award title.

DO $$
DECLARE
unresolved_count BIGINT;
    unresolved_courses TEXT;
BEGIN
SELECT
    COUNT(*),
    STRING_AGG(
        DISTINCT course.code || ' - ' || course.name,
            ', '
                ORDER BY course.code || ' - ' || course.name
    )
INTO
    unresolved_count,
    unresolved_courses
FROM public.graduation_applications graduation_application
         JOIN public.enrollments enrollment
              ON enrollment.id = graduation_application.enrollment_id
         JOIN public.courses course
              ON course.id = enrollment.course_id
WHERE graduation_application.award_title IS NULL
   OR BTRIM(graduation_application.award_title) = ''
   OR graduation_application.qualification_type IS NULL
   OR BTRIM(graduation_application.qualification_type) = '';

IF unresolved_count > 0 THEN
        RAISE EXCEPTION
            'Cannot complete graduation migration. % existing application(s) have no valid award title or qualification type. Courses: %',
            unresolved_count,
            COALESCE(unresolved_courses, 'Unknown');
END IF;
END
$$;


-- ============================================================================
-- 4. MAKE APPLICATION-TIME AWARD SNAPSHOTS REQUIRED
-- ============================================================================

ALTER TABLE public.graduation_applications
    ALTER COLUMN award_title SET NOT NULL,
ALTER COLUMN qualification_type SET NOT NULL;


-- ============================================================================
-- 5. ADD DATA-INTEGRITY CONSTRAINTS
-- ============================================================================

ALTER TABLE public.graduation_applications
    ADD CONSTRAINT chk_graduation_application_award_title_not_blank
        CHECK (BTRIM(award_title) <> ''),

    ADD CONSTRAINT chk_graduation_application_qualification_type_not_blank
        CHECK (BTRIM(qualification_type) <> ''),

    ADD CONSTRAINT chk_graduation_application_final_average_range
        CHECK (
            final_cumulative_average IS NULL
            OR (
                final_cumulative_average >= 0
                AND final_cumulative_average <= 100
            )
        );


-- ============================================================================
-- 6. ACADEMIC APPROVER FOREIGN KEY
-- ============================================================================
--
-- Users are stored in public.users in your current schema. :contentReference[oaicite:1]{index=1}

ALTER TABLE public.graduation_applications
    ADD CONSTRAINT fk_graduation_application_academic_approval_by
        FOREIGN KEY (academic_approval_by)
            REFERENCES public.users(id)
            ON DELETE RESTRICT;


-- ============================================================================
-- 7. INDEXES
-- ============================================================================

CREATE INDEX idx_graduation_application_academic_approval_by
    ON public.graduation_applications(academic_approval_by);

CREATE INDEX idx_graduation_application_award_classification
    ON public.graduation_applications(award_classification);

CREATE INDEX idx_graduation_application_status
    ON public.graduation_applications(status);


-- ============================================================================
-- 8. COLUMN DOCUMENTATION
-- ============================================================================

COMMENT ON COLUMN public.graduation_applications.award_title IS
    'Immutable snapshot of the official award title when the student submitted the graduation application.';

COMMENT ON COLUMN public.graduation_applications.qualification_type IS
    'Immutable snapshot of the course qualification type when the student submitted the graduation application.';

COMMENT ON COLUMN public.graduation_applications.final_cumulative_average IS
    'Final cumulative academic average calculated and frozen during academic graduation approval.';

COMMENT ON COLUMN public.graduation_applications.award_classification IS
    'Final award classification calculated and frozen during academic graduation approval.';

COMMENT ON COLUMN public.graduation_applications.academic_approval_by IS
    'User who finalized the cumulative average and award classification.';

COMMENT ON COLUMN public.graduation_applications.academic_approved_at IS
    'Date and time when the cumulative average and classification were finalized.';



-- Consolidated from V9__departmental_graduation_lists.sql

CREATE TABLE graduation_lists(id BIGSERIAL PRIMARY KEY,academic_year_id BIGINT NOT NULL REFERENCES academic_years(id),department_id BIGINT NOT NULL REFERENCES departments(id),status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',published_by BIGINT REFERENCES users(id),published_at TIMESTAMPTZ,submitted_by BIGINT REFERENCES users(id),submitted_at TIMESTAMPTZ,version BIGINT DEFAULT 0,CONSTRAINT uq_graduation_list_year_department UNIQUE(academic_year_id,department_id));
ALTER TABLE graduation_applications ADD COLUMN graduation_list_id BIGINT REFERENCES graduation_lists(id),ADD COLUMN admission_number_snapshot VARCHAR(80),ADD COLUMN course_code_snapshot VARCHAR(50),ADD COLUMN course_name_snapshot VARCHAR(200),ADD COLUMN hod_remarks VARCHAR(1000),ADD COLUMN details_confirmed_at TIMESTAMPTZ,ADD COLUMN finance_cleared BOOLEAN NOT NULL DEFAULT FALSE;
INSERT INTO graduation_lists(academic_year_id,department_id,status) SELECT DISTINCT e.current_academic_year_id,c.department_id,'SUBMITTED' FROM graduation_applications ga JOIN enrollments e ON e.id=ga.enrollment_id JOIN courses c ON c.id=e.course_id ON CONFLICT DO NOTHING;
UPDATE graduation_applications ga SET graduation_list_id=gl.id,admission_number_snapshot=s.admission_number,course_code_snapshot=c.code,course_name_snapshot=c.name FROM enrollments e JOIN students s ON s.id=e.student_id JOIN courses c ON c.id=e.course_id JOIN graduation_lists gl ON gl.academic_year_id=e.current_academic_year_id AND gl.department_id=c.department_id WHERE ga.enrollment_id=e.id;
ALTER TABLE graduation_applications ALTER COLUMN graduation_list_id SET NOT NULL;
CREATE INDEX idx_graduation_list_status ON graduation_lists(status);CREATE INDEX idx_graduation_entry_list_status ON graduation_applications(graduation_list_id,status);



-- Consolidated from V10__graduation_entry_rollover_and_names.sql

ALTER TABLE graduation_applications DROP CONSTRAINT IF EXISTS uq_graduation_application_enrollment;
ALTER TABLE graduation_applications ADD COLUMN graduation_name VARCHAR(180);
UPDATE graduation_applications ga SET graduation_name=s.full_name FROM enrollments e JOIN students s ON s.id=e.student_id WHERE ga.enrollment_id=e.id;
ALTER TABLE graduation_applications ALTER COLUMN graduation_name SET NOT NULL;
ALTER TABLE graduation_applications ADD CONSTRAINT uq_graduation_entry_list_enrollment UNIQUE(graduation_list_id,enrollment_id);



-- Consolidated from V11__graduation_missing_units_snapshot.sql

ALTER TABLE graduation_applications ADD COLUMN missing_units INTEGER;
UPDATE graduation_applications SET missing_units=GREATEST(COALESCE(required_units,0)-COALESCE(passed_units,0)-COALESCE(failed_units,0)-COALESCE(missing_results,0),0) WHERE missing_units IS NULL;



-- Consolidated from V12__remove_legacy_fee_structures.sql

-- The active fee configuration is period_fee_items + fee_items.
-- Remove both superseded fee-structure implementations and their stale links.
ALTER TABLE IF EXISTS fee_ledger DROP COLUMN IF EXISTS fee_structure_id;
ALTER TABLE IF EXISTS enrollments DROP COLUMN IF EXISTS fee_structure_id;

DROP TABLE IF EXISTS fee_structure_items_two CASCADE;
DROP TABLE IF EXISTS fee_structures_two CASCADE;
DROP TABLE IF EXISTS fee_structure_items CASCADE;
DROP TABLE IF EXISTS fee_structures CASCADE;

DELETE FROM role_permissions
WHERE permission_id IN (
    SELECT id FROM permissions
    WHERE name IN ('FEE_STRUCTURE_READ', 'FEE_STRUCTURE_MANAGE')
);

DELETE FROM permissions
WHERE name IN ('FEE_STRUCTURE_READ', 'FEE_STRUCTURE_MANAGE');



-- Consolidated from V13__clearance_workflow_stages.sql

ALTER TABLE academic_year_clearance_departments
    ADD COLUMN stage varchar(20),
    ADD COLUMN mandatory boolean NOT NULL DEFAULT true;

UPDATE academic_year_clearance_departments c
SET stage = CASE WHEN lower(trim(d.name)) = 'finance' THEN 'FINANCE' ELSE 'GENERAL' END
FROM departments d
WHERE d.id = c.department_id;

ALTER TABLE academic_year_clearance_departments ALTER COLUMN stage SET NOT NULL;

ALTER TABLE clearance_checks ADD COLUMN stage varchar(20);

UPDATE clearance_checks c
SET stage = CASE WHEN lower(trim(d.name)) = 'finance' THEN 'FINANCE' ELSE 'GENERAL' END
FROM departments d
WHERE d.id = c.department_id;

ALTER TABLE clearance_checks ALTER COLUMN stage SET NOT NULL;

CREATE INDEX idx_clearance_checks_workflow
    ON clearance_checks (application_id, stage, mandatory, status);



-- Consolidated from V14__public_uuids_for_enrollments_and_graduation_lists.sql

ALTER TABLE enrollments ADD COLUMN uuid uuid;
UPDATE enrollments SET uuid = gen_random_uuid() WHERE uuid IS NULL;
ALTER TABLE enrollments ALTER COLUMN uuid SET NOT NULL;
ALTER TABLE enrollments ADD CONSTRAINT uq_enrollments_uuid UNIQUE (uuid);

ALTER TABLE graduation_lists ADD COLUMN uuid uuid;
UPDATE graduation_lists SET uuid = gen_random_uuid() WHERE uuid IS NULL;
ALTER TABLE graduation_lists ALTER COLUMN uuid SET NOT NULL;
ALTER TABLE graduation_lists ADD CONSTRAINT uq_graduation_lists_uuid UNIQUE (uuid);



-- Consolidated from V15__graduation_candidate_clearance_stage.sql

ALTER TABLE graduation_applications
    ADD COLUMN clearance_stage varchar(30) NOT NULL DEFAULT 'NOT_STARTED';

UPDATE graduation_applications
SET clearance_stage = CASE
    WHEN status = 'FINANCE_REVIEW' THEN 'FINANCE_REVIEW'
    WHEN status = 'REGISTRAR_REVIEW' THEN 'REGISTRAR_REVIEW'
    WHEN status IN ('CLEARANCE_COMPLETE', 'APPROVED_FOR_GRADUATION', 'ASSIGNED_TO_BATCH', 'GRADUATED', 'CONFERRED') THEN 'COMPLETE'
    WHEN status IN ('CLEARANCE_IN_PROGRESS', 'ACTION_REQUIRED') THEN 'GENERAL_CLEARANCE'
    ELSE 'NOT_STARTED'
END;

CREATE INDEX idx_graduation_applications_clearance_queue
    ON graduation_applications (graduation_list_id, clearance_stage, status);



-- Consolidated from V16__align_graduation_application_statuses.sql

ALTER TABLE public.graduation_applications
    DROP CONSTRAINT IF EXISTS graduation_applications_status_check;

ALTER TABLE public.graduation_applications
    ADD CONSTRAINT graduation_applications_status_check
    CHECK (status IN (
        'DRAFT',
        'PROVISIONAL',
        'DETAILS_CONFIRMED',
        'CLEARANCE_IN_PROGRESS',
        'FINANCE_REVIEW',
        'REGISTRAR_REVIEW',
        'CLEARANCE_COMPLETE',
        'SUBMITTED_TO_REGISTRAR',
        'APPROVED_FOR_GRADUATION',
        'ACTION_REQUIRED',
        'REMOVED',
        'ASSIGNED_TO_BATCH',
        'GRADUATED',
        'CONFERRED',
        'REJECTED',
        'CANCELLED',
        'APPLIED',
        'READY_FOR_GRADUATION_REVIEW',
        'PENDING_GRADUATION',
        'APPROVED'
    ));



-- Consolidated from V17__remove_registrar_from_departmental_clearance.sql

DELETE FROM clearance_checks check_row
USING departments department
WHERE check_row.department_id = department.id
  AND lower(trim(department.name)) = 'registrar';

DELETE FROM academic_year_clearance_departments configured
USING departments department
WHERE configured.department_id = department.id
  AND lower(trim(department.name)) = 'registrar';

UPDATE graduation_applications candidate
SET clearance_stage = 'FINANCE_REVIEW',
    status = 'CLEARANCE_IN_PROGRESS',
    finance_cleared = false,
    clearance_complete = false
FROM graduation_lists graduation_list,
     clearance_applications clearance_application
WHERE candidate.graduation_list_id = graduation_list.id
  AND clearance_application.enrollment_id = candidate.enrollment_id
  AND clearance_application.academic_year_id = graduation_list.academic_year_id
  AND candidate.clearance_stage = 'GENERAL_CLEARANCE'
  AND EXISTS (
      SELECT 1 FROM clearance_checks finance_check
      WHERE finance_check.application_id = clearance_application.id
        AND finance_check.stage = 'FINANCE'
  )
  AND NOT EXISTS (
      SELECT 1 FROM clearance_checks general_check
      WHERE general_check.application_id = clearance_application.id
        AND general_check.stage = 'GENERAL'
        AND general_check.mandatory = true
        AND general_check.status <> 'CLEARED'
  );



-- Consolidated from V18__certificate_classification_snapshot.sql

ALTER TABLE graduation_certificates
    ADD COLUMN award_classification varchar(120);

UPDATE graduation_certificates certificate
SET award_classification = CASE application.award_classification
    WHEN 'FIRST_CLASS_HONOURS' THEN 'First Class Honours'
    WHEN 'SECOND_CLASS_HONOURS_UPPER_DIVISION' THEN 'Second Class Honours (Upper Division)'
    WHEN 'SECOND_CLASS_HONOURS_LOWER_DIVISION' THEN 'Second Class Honours (Lower Division)'
    WHEN 'DISTINCTION' THEN 'Distinction'
    WHEN 'MERIT' THEN 'Merit'
    WHEN 'CREDIT' THEN 'Credit'
    WHEN 'PASS' THEN 'Pass'
    ELSE replace(initcap(replace(application.award_classification, '_', ' ')), 'Honours', 'Honours')
END
FROM graduation_applications application
WHERE certificate.graduation_application_id = application.id
  AND application.award_classification IS NOT NULL;



-- Consolidated from V19__enforce_registrar_graduation_stage.sql

-- Registrar approval belongs to the graduation workflow, never departmental clearance.
-- Repeat the cleanup because an older running application may have inserted rows after V17.
DELETE FROM clearance_checks clearance_check
USING departments department
WHERE clearance_check.department_id = department.id
  AND lower(trim(department.name)) = 'registrar';

DELETE FROM academic_year_clearance_departments configured_department
USING departments department
WHERE configured_department.department_id = department.id
  AND lower(trim(department.name)) = 'registrar';

-- Advance candidates whose only remaining general blocker was the invalid Registrar check.
UPDATE graduation_applications candidate
SET clearance_stage = 'FINANCE_REVIEW',
    status = 'CLEARANCE_IN_PROGRESS',
    finance_cleared = false,
    clearance_complete = false
FROM graduation_lists graduation_list,
     clearance_applications clearance_application
WHERE candidate.graduation_list_id = graduation_list.id
  AND clearance_application.enrollment_id = candidate.enrollment_id
  AND clearance_application.academic_year_id = graduation_list.academic_year_id
  AND candidate.clearance_stage = 'GENERAL_CLEARANCE'
  AND EXISTS (
      SELECT 1
      FROM clearance_checks finance_check
      WHERE finance_check.application_id = clearance_application.id
        AND finance_check.stage = 'FINANCE'
  )
  AND NOT EXISTS (
      SELECT 1
      FROM clearance_checks general_check
      WHERE general_check.application_id = clearance_application.id
        AND general_check.stage = 'GENERAL'
        AND general_check.mandatory = true
        AND general_check.status <> 'CLEARED'
  );

-- Database-level protection prevents stale deployments or direct SQL from recreating it.
CREATE OR REPLACE FUNCTION reject_registrar_clearance_department()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM departments department
        WHERE department.id = NEW.department_id
          AND lower(trim(department.name)) = 'registrar'
    ) THEN
        RAISE EXCEPTION 'Registrar is a graduation approval stage and cannot be a clearance department';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_no_registrar_clearance_check ON clearance_checks;
CREATE TRIGGER trg_no_registrar_clearance_check
BEFORE INSERT OR UPDATE OF department_id ON clearance_checks
FOR EACH ROW EXECUTE FUNCTION reject_registrar_clearance_department();

DROP TRIGGER IF EXISTS trg_no_registrar_clearance_configuration ON academic_year_clearance_departments;
CREATE TRIGGER trg_no_registrar_clearance_configuration
BEFORE INSERT OR UPDATE OF department_id ON academic_year_clearance_departments
FOR EACH ROW EXECUTE FUNCTION reject_registrar_clearance_department();



-- Consolidated from V20__support_cash_payment_ledger_type.sql

ALTER TABLE fee_ledger DROP CONSTRAINT IF EXISTS fee_ledger_transaction_type_check;

ALTER TABLE fee_ledger ADD CONSTRAINT fee_ledger_transaction_type_check CHECK (
    transaction_type IN (
        'TUITION_BILL','ACCOMMODATION_BILL','PENALTY_FEE','PAYMENT_MPESA','PAYMENT_BANK','PAYMENT_CASH',
        'BURSARY_ALLOCATION','FEE_WAIVER','FEES_INVOICE','RESIT_FEE','RETAKE_FEE','GRADUATION_FEE',
        'MANUAL_DEBIT','SPONSOR_CREDIT','LOAN_CREDIT','MANUAL_CREDIT','REVERSAL',
        'MIGRATION_OPENING_DEBIT','MIGRATION_OPENING_CREDIT'
    )
);

